nolist

org &4000
write direct "a:CS.bin"

.PlayerFrameList
    defw PlayerSprite0 ; &255
    defw PlayerSprite1 ; &22d
    defw PlayerSprite2 ; &1f9
    defw PlayerSprite3 ; &1dd
    defw PlayerSprite4 ; &1e1
    defw PlayerSprite5 ; &20d
    defw PlayerSprite6 ; &22f
    defw PlayerSprite4 ; dummy entry
.PlayerFrameGrindList
    defw PlayerSpriteGrind0 ;
    defw PlayerSpriteGrind1 ;
    defw PlayerSpriteGrind2 ;
    defw PlayerSpriteGrind3 ;
    defw PlayerSpriteGrind4 ;
    defw PlayerSpriteGrind5 ;
    defw PlayerSpriteGrind6 ;
    defw PlayerSpriteGrind4 ;
.LaserFrameList
    defw LaserFrame0 ; &128
    defw LaserFrame5 ; &12b
    defw LaserFrame4 ; &12e
    defw LaserFrame3 ; &131
    defw LaserFrame2 ; &e9
    defw LaserFrame1 ; &bc
    defw LaserFrame1 ; dummy entry
    defw LaserFrame1 ; dummy entry

; the following compiled sprites were primarily autogenerated with some code
; they follow the same sequence for printing the sprites as the code for printing
; normal sprites you will find in EG_Sprites10.asm
; the tool used automatically commented out 0 bytes, but did not determine what if
; any redundant incs/decs could be commented out, so the compiled sprite code could
; be more efficient than it is here
read "EG_sprites_player.asm"
read "EG_sprites_laser.asm"
read "EG_sprites_player_grind.asm"
.laserframeend
; wave data for level also stored in compiled sprite bank.  has been modified from C64 original data
read "eg_wave_data_converted.asm"