"""export_palette.py - assets/art/palette.png -> src/data/palette.asm, the
sixteen bytes setup_display writes to the Video ULA.

The palette used to be a loop in src/bank0.asm that computed logical n ->
physical n & 7. It is a file now because Layer 8 makes the artist's PNGs the
source of the artwork, and an artist who paints a colour must be painting a
palette entry - so the palette and the sheets have to be one thing, checked
against each other, rather than a table in the assembler that nothing verifies.

MODE 2 (today): &FE21 takes (logical << 4) OR (physical EOR 7). All eight
physical colours are on screen at once and there is no choosing them, so every
palette entry must BE one of the eight; the exporter refuses anything else and
names the offending entry. Entries 8-15 alias 0-7 - the game uses that, logical
8 being the sprite engine's second black (logical 0 is its transparency key).

NULA (later, --nula): &FE23 takes two bytes per entry, (logical << 4) OR red
then (green << 4) OR blue, each channel the top nibble of the 8-bit value. The
sixteen entries then stop aliasing and become sixteen free 12-bit colours, and
NOTHING ELSE in the pipeline changes: chars.bin and the sprite banks already
store a full 4-bit logical per fat pixel, and the mask and flash LUTs work on
nibbles. Logical 0 stays the transparency key under both.

Run from the project root: python tools/export_palette.py [--nula]
"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "art"))
import bbc      # noqa: E402
import palette  # noqa: E402

OUT = "src/data/palette.asm"


def mode2_bytes(pal):
    physical = {tuple(rgb): n for n, rgb in enumerate(bbc.BBC_RGB)}
    out = []
    for n, rgb in enumerate(pal):
        if tuple(rgb) not in physical:
            raise SystemExit(
                f"{palette.PALETTE_PNG}: entry {n} is {tuple(rgb)}, which MODE 2 "
                "has not got. Only the eight BBC colours are legal without a "
                "NULA; run with --nula once there is one.")
        out.append((n << 4) | (physical[tuple(rgb)] ^ 7))
    return out


def nula_bytes(pal):
    out = []
    for n, (r, g, b) in enumerate(pal):
        out.append((n << 4) | (r >> 4))
        out.append(((g >> 4) << 4) | (b >> 4))
    return out


def main(nula=False, cpc=False):
    """MODE 2 from assets/art/palette.png; NuLA from the source palette the
    art was drawn at (tools/art/nula.py), because a NuLA build is the original
    artwork at its own colours and not the artist's sheets."""
    if nula:
        sys.path.insert(0, os.path.join(os.path.dirname(__file__), "art"))
        import nula as nulaart
        pal = nulaart.palette(cpc=cpc)
        out = OUT.replace("palette.asm",
                          "palette-nula%s.asm" % ("-cpc" if cpc else ""))
        what = "the Amstrad's sixteen mode 0 pens" if cpc else "the C64's sixteen"
    else:
        pal = palette.load()
        out = OUT
        what = palette.PALETTE_PNG

    data = nula_bytes(pal) if nula else mode2_bytes(pal)
    reg = "&FE23 (VideoNuLA palette)" if nula else "&FE21 (Video ULA)"
    lines = [
        r"\ Generated by tools/export_palette.py - do not edit.",
        rf"\ {what} as the bytes setup_display writes to {reg}.",
        r"\ ASCENDING, entry 0 first, which is the order the loop runs in and",
        r"\ the order VideoNuLA requires: each entry is TWO bytes, [index|red]",
        r"\ then [green|blue], and they must reach &FE23 in that order.",
        "",
        f"PAL_BYTES = {len(data)}",
        ".pal_data",
    ]
    step = 2 if nula else 1
    for n in range(16):
        vals = ", ".join(f"&{v:02X}" for v in data[n * step:n * step + step])
        r, g, b = pal[n]
        lines.append(rf"    EQUB {vals:<12}\ logical {n:<2} = &{r:02X}{g:02X}{b:02X}")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"{out} {len(data)} bytes, {'NuLA' if nula else 'MODE 2'}")
    if not nula:
        alias = [n for n in range(8, 16) if tuple(pal[n]) != tuple(pal[n - 8])]
        if alias:
            print(f"  note: logicals {alias} do not alias their low counterpart; "
                  "MODE 2 shows them as their physical colour anyway")
    else:
        print(f"  {len(set(pal))} distinct colours over 16 entries")


if __name__ == "__main__":
    main(nula="--nula" in sys.argv[1:], cpc="--cpc" in sys.argv[1:])
