\ ******************************************************************
\ *	bank3.asm
\ *	Sideways RAM bank 3 (slot SWRAM_COMPILED): straight-line 6502 for
\ *	the frames worth compiling (decision 29). Generated by
\ *	tools/compile_sprites.py; regenerate with the tool rather than
\ *	editing src/data.
\ *
\ *	A compiled body reads no sprite data - every pixel is an immediate -
\ *	so it does not belong to either pixel shift and both live here
\ *	together. That also gives the restore one bank to page in and
\ *	nothing to remember about which shift drew the sprite.
\ *
\ *	&8000  descriptors, four bytes a frame: draw lo/hi, restore lo/hi.
\ *	       spr_comp_lo/hi in the sprite banks point at these.
\ *	&8200  the bodies.
\ ******************************************************************

CLEAR 0,&FFFF
ORG &8000
GUARD &C000
.bank3_start

.compiled_data
INCBIN "src/data/compiled.bin"

.bank3_end

SAVE "BANK3", bank3_start, bank3_end

PRINT "------"
PRINT "BANK 3 - compiled sprite bodies"
PRINT "------"
PRINT "DATA size =",~bank3_end-bank3_start
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~&C000-P%
PRINT "------"
