\ ******************************************************************
\ *	bank1.asm
\ *	Sideways RAM bank 1 (slot SWRAM_SPRITES0): the sprite data for
\ *	pixel shift 0 - tables, then bounding-boxed MODE 2 frames.
\ *	Generated by tools/export_sprites.py; the layout is documented
\ *	there and mirrored by the constants at the top of src/sprite.asm.
\ *
\ *	After it, and sharing the bank because nothing on the titles page
\ *	reads a sprite: the zoom scroller (Layer 6e) - its font, its
\ *	message, its own four-cycle rupture, and the code that drives them.
\ ******************************************************************

CLEAR 0,&FFFF
ORG &8000
GUARD &C000
.bank1_start

.sprite_bank_0
IF GFX_CPC
INCBIN "src/data/sprites0-cpc.bin"
ELSE
INCBIN "src/data/sprites0.bin"
ENDIF

\ ******************************************************************
\ *	Layer 6e: the titles page's zoom scroller
\ ******************************************************************
\ *	The C64's `zoom_mover` shifts six character rows left a whole
\ *	character a frame and writes one new column of block-or-blank at
\ *	the right-hand edge, then copies the lot into a second band
\ *	rotated 180 degrees. We do none of the shifting and none of the
\ *	copying: each band is its own CRTC cycle, hardware-scrolled by
\ *	R12/R13 round an 8K ring, and all that is left is the original's
\ *	own new-column write - six rows of one cell.
\ *
\ *	Our rows are 640 contiguous bytes and the CPC's are not, so a band
\ *	whose start address moves SHEARS: row r gains, at its right edge,
\ *	the byte column row r+1 has just lost. Writing the incoming cell
\ *	into every row pays exactly that off, because an address written
\ *	for row r is written again for row r-1 eighty steps later, which
\ *	is the step the display migrates it. `scroll_advance` and
\ *	`col_copy` have been doing the same thing for the play area since
\ *	Layer 2.
\ *
\ *	One field, one cell: the C64's own rate and granularity. There is
\ *	no double buffer here - both banks are on screen inside the same
\ *	frame - so the titles are not on the 25 Hz lock the game needs,
\ *	and decision 23's doubling does not apply.
\ *
\ *	All of it reached through bank_call in main RAM. Nothing in a
\ *	sideways bank can page its own bank out from under itself.
\ ******************************************************************

.ttl_font                       ; 32 glyphs x 8 bytes, 1bpp, rows 1-6 inked
INCBIN "src/data/zoom.bin"
ttl_block   = ttl_font + 256    ; character $8e rendered: 16 bytes, one cell
ttl_message = ttl_font + 272    ; glyph numbers, &FF ends it

.ttl_blank
EQUB 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

\ ---- state. In the bank with the code: the foreground reaches it through
\ bank_call and the IRQ pages this bank in, so nobody needs it in main RAM.
.ttl_top    EQUW 0              ; R12/R13 for the top band: address / 8
.ttl_bot    EQUW 0              ; and the bottom band's
.ttl_zbuf   EQUB 0, 0, 0, 0, 0, 0, 0, 0     ; the glyph being shifted out
.ttl_bit    EQUB 0              ; which of its eight columns is next
.ttl_bits_t EQUB 0              ; this cell's six rows, bit 5 = row 0
.ttl_bits_b EQUB 0              ; the same shifted up two, for ASL
.zm_bits    EQUB 0              ; the copy zm_write_band shifts

\ ******************************************************************
\ *	ttl_init - start the message and park both rings
\ ******************************************************************

.ttl_init
    lda #LO(TTL_RING/8) : sta ttl_top   : sta ttl_bot
    lda #HI(TTL_RING/8) : sta ttl_top+1 : sta ttl_bot+1
    lda #LO(ttl_message) : sta ttl_read+1
    lda #HI(ttl_message) : sta ttl_read+2
    lda #0
    sta ttl_bit
    rts

\ ******************************************************************
\ *	ttl_next_glyph - eight more bits a row, and the message pointer
\ ******************************************************************
\ *	Self-modifying over the message exactly as the C64's `mess_read`
\ *	is, and for the same reason: the pointer has to survive a frame
\ *	and the zero page here is scratch.
\ *
\ *	The terminator is &FF, not the original's 0: `scrolltext` holds
\ *	screen codes, where 0 is the unused '@', and this holds decoded
\ *	glyph numbers, where 0 is the blank.

.ttl_next_glyph
.ttl_read
    lda ttl_message             ; SELF-MODIFIED
    cmp #&ff
    bne ttl_ng_ok
    lda #LO(ttl_message) : sta ttl_read+1
    lda #HI(ttl_message) : sta ttl_read+2
    lda ttl_message             ; the message never starts with its own end
.ttl_ng_ok
    asl a : asl a : asl a       ; 32 glyphs of 8 bytes: 248 fits a byte
    tax
    ldy #0
.ttl_ng_copy
    lda ttl_font, x
    sta ttl_zbuf, y
    inx
    iny
    cpy #8
    bne ttl_ng_copy
    inc ttl_read+1
    bne ttl_ng_done
    inc ttl_read+2
.ttl_ng_done
    rts

\ ******************************************************************
\ *	ttl_cell - one zoom cell's worth of bits, for both bands
\ ******************************************************************
\ *	The C64's own six `asl zoom_buffer+n`, carry deciding block or
\ *	blank. Rows 1-6 of the glyph, which is why the band is six high:
\ *	rows 0 and 7 of every glyph in this font are blank.
\ *
\ *	Rolled up, bit 5 is row 0 and bit 0 is row 5. The bottom band
\ *	wants rows 0 downwards, so it takes the copy shifted up two and
\ *	ASLs; the top band is the 180-degree rotation and wants rows 5
\ *	upwards, so it LSRs the same byte. That is the whole of the
\ *	vertical flip - `zoom_mirror` does not survive into this port.

.ttl_cell
    lda ttl_bit
    bne ttl_c_shift
    jsr ttl_next_glyph
.ttl_c_shift
    inc ttl_bit
    lda ttl_bit
    and #7
    sta ttl_bit

    lda #0
    sta ttl_bits_t
    ldx #0
.ttl_c_row
    asl ttl_zbuf+1, x
    rol ttl_bits_t
    inx
    cpx #TTL_BAND_ROWS
    bne ttl_c_row

    lda ttl_bits_t
    asl a
    asl a
    sta ttl_bits_b
    rts

\ ******************************************************************
\ *	zm_write_band - one cell into all six rows of a band
\ ******************************************************************
\ *	write_ptr = the cell address for row 0, already inside the ring.
\ *	zm_bits holds the six bits and zm_shift is patched to ASL or LSR
\ *	to say which end of them this band reads from.
\ *
\ *	The +640 wraps at the top of the ring: the display's own 8K wrap
\ *	does the same thing to the address the CRTC is fetching, and the
\ *	two have to agree or the write lands where the picture is not.

.zm_write_band
    ldx #TTL_BAND_ROWS
.zm_row
.zm_shift
    asl zm_bits                 ; SELF-MODIFIED: LSR for the top band
    bcs zm_solid
    lda #LO(ttl_blank) : sta read_ptr
    lda #HI(ttl_blank) : sta read_ptr+1
    bne zm_draw                 ; a bank address: the high byte is never 0
.zm_solid
    lda #LO(ttl_block) : sta read_ptr
    lda #HI(ttl_block) : sta read_ptr+1
.zm_draw
    ldy #TTL_CELL-1
.zm_copy
    lda (read_ptr), y
    sta (write_ptr), y
    dey
    bpl zm_copy

    clc
    lda write_ptr   : adc #LO(row_stride) : sta write_ptr
    lda write_ptr+1 : adc #HI(row_stride)
    cmp #HI(TTL_RING + TTL_RING_SIZE)
    bcc zm_wrapped
    sbc #HI(TTL_RING_SIZE)
.zm_wrapped
    sta write_ptr+1
    dex
    bne zm_row
    rts

\ ******************************************************************
\ *	ttl_frame - one field of the titles page
\ ******************************************************************
\ *	Called straight after the VSync handler has returned, which is
\ *	where the two windows are. Each band's memory is fetched only
\ *	during its own cycle, so the top band - rows 5 to 10 - has to be
\ *	finished by row 5 and the bottom band - rows 19 to 24 - by row 19.
\ *	The top one goes first for that reason.
\ *
\ *	The ring pointers move under SEI because the IRQ reads them: the
\ *	top band's at fire 1, absolute row 2, and the bottom band's at
\ *	fire 4, absolute row 12.

.ttl_frame
    jsr ttl_cell

    \ ---- the top band: MAIN, and the picture rotated 180 degrees, so
    \ the window walks BACKWARDS and the new cell enters at the left.
    lda ttl_bits_t : sta zm_bits
    lda #&4e : sta zm_shift             ; LSR abs
    php : sei
    sec
    lda ttl_top   : sbc #TTL_CELL/8 : sta ttl_top
    lda ttl_top+1 : sbc #0
    cmp #HI(TTL_RING/8)
    bcs ttl_f_tok
    adc #HI(TTL_RING_SIZE/8)            ; carry is clear here
.ttl_f_tok
    sta ttl_top+1
    sta write_ptr+1
    lda ttl_top : sta write_ptr
    plp
    asl write_ptr : rol write_ptr+1     ; the CRTC unit is eight bytes
    asl write_ptr : rol write_ptr+1
    asl write_ptr : rol write_ptr+1
    lda &fe34
    and #&ff - 4                        ; X = 0: the CPU writes MAIN
    sta &fe34
    jsr zm_write_band

    \ ---- the bottom band: SHADOW, the message the right way up, the
    \ window walking forwards and the new cell entering at the right.
    lda ttl_bits_b : sta zm_bits
    lda #&0e : sta zm_shift             ; ASL abs
    php : sei
    clc
    lda ttl_bot   : adc #TTL_CELL/8 : sta ttl_bot
    lda ttl_bot+1 : adc #0
    cmp #HI((TTL_RING + TTL_RING_SIZE)/8)
    bcc ttl_f_bok
    sbc #HI(TTL_RING_SIZE/8)
.ttl_f_bok
    sta ttl_bot+1
    sta write_ptr+1
    lda ttl_bot : sta write_ptr
    plp
    asl write_ptr : rol write_ptr+1
    asl write_ptr : rol write_ptr+1
    asl write_ptr : rol write_ptr+1
    clc                                 ; the last cell of the row
    lda write_ptr   : adc #LO(row_stride - TTL_CELL) : sta write_ptr
    lda write_ptr+1 : adc #HI(row_stride - TTL_CELL)
    cmp #HI(TTL_RING + TTL_RING_SIZE)
    bcc ttl_f_bw
    sbc #HI(TTL_RING_SIZE)
.ttl_f_bw
    sta write_ptr+1
    lda &fe34
    ora #4                              ; X = 1: the CPU writes SHADOW
    sta &fe34
    jmp zm_write_band


\ ******************************************************************
\ *	The credits raster (Layer 6e, decisions 2 and 3 of the layer)
\ ******************************************************************
\ *	The C64's `ttl_pulse` is a HORIZONTAL colour-RAM cycle along the
\ *	first and last credit lines, running in opposite directions. MODE
\ *	2 has no colour RAM, so it cannot be transcribed; the CPC hit the
\ *	same wall and turned the effect through ninety degrees, and this
\ *	is `TitleRaster` ported - eight scanlines of palette writes per
\ *	line, the same list indexed from opposite ends.
\ *
\ *	The colours are the CPC's own `RasterPal`, decoded through the
\ *	Gate Array table and collapsed to MODE 2's eight by hue exactly as
\ *	decision 41 collapses the artwork. It is a heat pulse: the body
\ *	runs red, blue, bright red, purple, orange, pink, bright yellow,
\ *	pastel yellow, bright white and back down, and the trailing colour
\ *	follows four steps behind. Steps 9-15 are 7 down to 1, so sixteen
\ *	steps ping-pong over nine colours; the last eight repeat the first
\ *	eight so an eight-step window starting at step 15 can run off the
\ *	end, as the CPC's does.
\ *
\ *	The collapse doubles three of the nine steps - bright red and
\ *	orange land on red with plain red, pastel yellow on yellow with
\ *	bright yellow, pink on magenta with purple - so nine colours
\ *	become six. Faithful, and KC's eye has the last word on it.
\ *
\ *	Our credits are drawn in blue, cyan and white by export_title.py's
\ *	PAIR_COLOUR, and pair 3 - white, logical 7 - is the one the C64
\ *	pulses through colour RAM. So logical 7 takes the body list and
\ *	logical 6 the trailing one, and logical 4 is left as the shadow.
\ ******************************************************************

.ttl_pal
EQUB &76, &67, &73, &67, &76, &66, &72, &66
EQUB &76, &63, &72, &63, &74, &66, &74, &66
EQUB &70, &66, &74, &66, &74, &66, &72, &63
EQUB &76, &63, &72, &66, &76, &66, &73, &67
EQUB &76, &67, &73, &67, &76, &66, &72, &66
EQUB &76, &63, &72, &63, &74, &66, &74, &66

TTL_PAL_STEPS = 16              ; before the repeat; the window is eight long
TTL_RASTER_ROWS = 8             ; one character row

.ttl_pulse  EQUB 0              ; 0-31; one step every two fields, as the C64
.ttl_rcount EQUB 0

\ ******************************************************************
\ *	ttl_raster - one credit line's eight scanlines
\ ******************************************************************
\ *	X = the first step, as a byte offset into ttl_pal. Called from
\ *	inside the IRQ, so interrupts are already off and the only thing
\ *	that can move the timing is where the fire landed.
\ *
\ *	The loop is padded to one scanline. Every iteration starts with a
\ *	write to &FE21, which is on the 1 MHz bus, so the CPU stalls to
\ *	the same phase each time and the loop cannot drift by an odd
\ *	cycle - which is what makes a padded loop stable enough to do
\ *	this at all. TTL_RASTER_PAD is tuned by looking at the screen.

TTL_RASTER_PAD = 18

.ttl_raster
    lda #TTL_RASTER_ROWS
    sta ttl_rcount
.ttl_r_line
    lda ttl_pal, x
    sta VIDEO_ULA_PAL
    lda ttl_pal+1, x
    sta VIDEO_ULA_PAL
    inx
    inx
    ldy #TTL_RASTER_PAD
.ttl_r_pad
    dey
    bne ttl_r_pad
    dec ttl_rcount
    bne ttl_r_line

    \ and back to what setup_display set, before the panel sees it
    lda #&70 + (7 EOR 7)                ; logical 7 -> white
    sta VIDEO_ULA_PAL
    lda #&60 + (6 EOR 7)                ; logical 6 -> cyan
    sta VIDEO_ULA_PAL
    rts

\ ******************************************************************
\ *	ttl_rupt_timer - the titles' four-cycle rupture
\ ******************************************************************
\ *	Called from rupt_timer in main RAM, which pages this bank in and
\ *	puts &F4's bank back afterwards. Here rather than in main RAM
\ *	because main RAM has 145 bytes and this is more than that.
\ *
\ *	  fire 1  abs  2  A row 2   R4 for A; R6 and R12/13 for B
\ *	  fire 2  abs  7  B row 2   R4 for B, which C inherits unchanged;
\ *	                            R6 and R12/13 for C
\ *	  fire 3  abs 11  B row 6   the display bank -> SHADOW. B's
\ *	                            seventh row is fetched by nobody, so
\ *	                            the write has a row of slack
\ *	  fire 4  abs 12  C row 0   R6 and R12/13 for D
\ *	  fire 5  abs 17  C row 5   (the second raster, when there is one)
\ *	  fire 6  abs 20  D row 1   R4 for D
\ *
\ *	R7 is a constant, as it is in the game: 15 is past the end of A,
\ *	B and C, and can only be reached in D.

.ttl_rupt_timer
    lda rupt_state
    bne ttl_rt_not1

    \ ---- fire 1: A row 2 ----
    CRTC 4, TTL_PANEL_R4                ; A's own
    CRTC 6, TTL_BAND_ROWS               ; for B
    lda #12 : sta CRTC_ADDR : lda ttl_top+1 : sta CRTC_DATA
    lda #13 : sta CRTC_ADDR : lda ttl_top   : sta CRTC_DATA
    lda #LO(TTL_T1_I3) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I3) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not1
    cmp #1
    bne ttl_rt_not2

    \ ---- fire 2: B row 2 ----
    CRTC 4, TTL_BAND_R4                 ; B's own, and C is the same shape
    CRTC 6, TTL_BAND_ROWS               ; for C
    CRTC 12, HI(TTL_CRED/8)
    CRTC 13, LO(TTL_CRED/8)
    lda #LO(TTL_T1_I4) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I4) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not2
    cmp #2
    bne ttl_rt_not3

    \ ---- fire 3: B row 6, the blank one ----
    lda &fe34
    ora #1                              ; D = 1: display SHADOW for C and D
    sta &fe34
    lda #LO(TTL_T1_I5) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I5) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not3
    cmp #3
    bne ttl_rt_not4

    \ ---- fire 4: C row 0, the first credit line ----
    \ The raster FIRST: it has to start on the row's first scanline, and
    \ D's registers only have to be written some time inside C, which
    \ runs to absolute row 18.
    lda ttl_pulse
    and #TTL_PAL_STEPS * 2 - 2          ; the CPC's own AND &1E
    tax
    jsr ttl_raster
    CRTC 6, TTL_BAND_ROWS               ; for D
    lda #12 : sta CRTC_ADDR : lda ttl_bot+1 : sta CRTC_DATA
    lda #13 : sta CRTC_ADDR : lda ttl_bot   : sta CRTC_DATA
    lda #LO(TTL_T1_I6) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I6) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not4
    cmp #4
    bne ttl_rt_not5

    \ ---- fire 5: C row 5, the last credit line ----
    \ Indexed from the other end of the list, which is the CPC's own
    \ neg / add 30, and is what makes the two lines run opposite ways -
    \ as the C64's two colour-RAM lines do.
    lda ttl_pulse
    and #TTL_PAL_STEPS * 2 - 2
    sta ttl_rcount
    lda #TTL_PAL_STEPS * 2 - 2
    sec
    sbc ttl_rcount
    tax
    jsr ttl_raster
    lda #LO(T1_I3) : sta SYS_VIA_T1LL   ; the long dummy: VSync restarts T1
    lda #HI(T1_I3) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not5
    cmp #5
    bne ttl_rt_done

    \ ---- fire 6: D row 1 ----
    \ R4 has to be written inside its own cycle, and D is the only cycle
    \ this can be done from - see the note in main.asm.
    CRTC 4, TTL_LAST_R4
    inc rupt_state

    \ and the pulse on a step, one every two fields as ttl_pulse_tmr does
    inc ttl_pulse
    lda ttl_pulse
    and #TTL_PAL_STEPS * 2 - 1
    sta ttl_pulse
.ttl_rt_done
    rts

.bank1_end

SAVE "BANK1", bank1_start, bank1_end

PRINT "------"
PRINT "BANK 1 - sprites, shift 0, and the titles' zoom scroller"
PRINT "------"
PRINT "DATA size =",~bank1_end-bank1_start
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~&C000-P%
PRINT "------"
