\ ******************************************************************
\ *	bank1.asm
\ *	Sideways RAM bank 1 (slot SWRAM_SPRITES0): the sprite data for
\ *	pixel shift 0 - tables, then bounding-boxed MODE 2 frames.
\ *	Generated by tools/export_sprites.py; the layout is documented
\ *	there and mirrored by the constants at the top of src/sprite.asm.
\ *
\ *	After it, and sharing the bank because nothing on the titles page
\ *	reads a sprite: the zoom scroller (Layer 6e) - its font, its
\ *	message, its own four-cycle rupture, and the code that drives them.
\ ******************************************************************

CLEAR 0,&FFFF
ORG &8000
GUARD &C000
.bank1_start

.sprite_bank_0
IF GFX_CPC
INCBIN "src/data/sprites0-cpc.bin"
ELSE
INCBIN "src/data/sprites0.bin"
ENDIF

\ ******************************************************************
\ *	Layer 6e: the titles page's zoom scroller
\ ******************************************************************
\ *	The C64's `zoom_mover` shifts six character rows left a whole
\ *	character a frame and writes one new column of block-or-blank at
\ *	the right-hand edge, then copies the lot into a second band
\ *	rotated 180 degrees. We do none of the shifting and none of the
\ *	copying: each band is its own CRTC cycle, hardware-scrolled by
\ *	R12/R13 round an 8K ring, and all that is left is the original's
\ *	own new-column write - six rows of one cell.
\ *
\ *	Our rows are 640 contiguous bytes and the CPC's are not, so a band
\ *	whose start address moves SHEARS: row r gains, at its right edge,
\ *	the byte column row r+1 has just lost. Writing the incoming cell
\ *	into every row pays exactly that off, because an address written
\ *	for row r is written again for row r-1 eighty steps later, which
\ *	is the step the display migrates it. `scroll_advance` and
\ *	`col_copy` have been doing the same thing for the play area since
\ *	Layer 2.
\ *
\ *	One field, one cell: the C64's own rate and granularity. There is
\ *	no double buffer here - both banks are on screen inside the same
\ *	frame - so the titles are not on the 25 Hz lock the game needs,
\ *	and decision 23's doubling does not apply.
\ *
\ *	All of it reached through bank_call in main RAM. Nothing in a
\ *	sideways bank can page its own bank out from under itself.
\ ******************************************************************

.ttl_font                       ; 32 glyphs x 8 bytes, 1bpp, rows 1-6 inked
INCBIN "src/data/zoom.bin"
ttl_block   = ttl_font + 256    ; character $8e rendered: 16 bytes, one cell
ttl_message = TTL_SCROLL        ; glyph numbers, &FF ends it - and NOT in
                                ; this bank any more (Layer 9f). It rides
                                ; in the PANEL file and lands at &3C80,
                                ; where assets/scrolltext.txt has room to
                                ; grow; behind the font here it had eleven
                                ; bytes. Main RAM, and readable from a
                                ; paged-in bank like any other

.ttl_blank
EQUB 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

\ ---- state. In the bank with the code: the foreground reaches it through
\ bank_call and the IRQ pages this bank in, so nobody needs it in main RAM.
.ttl_top    EQUW 0              ; R12/R13 for the top band: address / 8
.ttl_bot    EQUW 0              ; and the bottom band's
.ttl_zbuf   EQUB 0, 0, 0, 0, 0, 0, 0, 0     ; the glyph being shifted out
.ttl_bit    EQUB 0              ; which of its eight columns is next
.ttl_bits_t EQUB 0              ; this cell's six rows, bit 5 = row 0
.ttl_bits_b EQUB 0              ; the same shifted up two, for ASL
.zm_bits    EQUB 0              ; the copy zm_write_band shifts

\ ******************************************************************
\ *	ttl_init - start the message and park both rings
\ ******************************************************************

.ttl_init
    lda #LO(TTL_RING/8) : sta ttl_top   : sta ttl_bot
    lda #HI(TTL_RING/8) : sta ttl_top+1 : sta ttl_bot+1
    lda #LO(ttl_message) : sta ttl_read+1
    lda #HI(ttl_message) : sta ttl_read+2
    lda #0
    sta ttl_bit
    rts

\ ******************************************************************
\ *	ttl_next_glyph - eight more bits a row, and the message pointer
\ ******************************************************************
\ *	Self-modifying over the message exactly as the C64's `mess_read`
\ *	is, and for the same reason: the pointer has to survive a frame
\ *	and the zero page here is scratch.
\ *
\ *	The terminator is &FF, not the original's 0: `scrolltext` holds
\ *	screen codes, where 0 is the unused '@', and this holds decoded
\ *	glyph numbers, where 0 is the blank.

.ttl_next_glyph
.ttl_read
    lda ttl_message             ; SELF-MODIFIED
    cmp #&ff
    bne ttl_ng_ok
    lda #LO(ttl_message) : sta ttl_read+1
    lda #HI(ttl_message) : sta ttl_read+2
    lda ttl_message             ; the message never starts with its own end
.ttl_ng_ok
    asl a : asl a : asl a       ; 32 glyphs of 8 bytes: 248 fits a byte
    tax
    ldy #0
.ttl_ng_copy
    lda ttl_font, x
    sta ttl_zbuf, y
    inx
    iny
    cpy #8
    bne ttl_ng_copy
    inc ttl_read+1
    bne ttl_ng_done
    inc ttl_read+2
.ttl_ng_done
    rts

\ ******************************************************************
\ *	ttl_cell - one zoom cell's worth of bits, for both bands
\ ******************************************************************
\ *	The C64's own six `asl zoom_buffer+n`, carry deciding block or
\ *	blank. Rows 1-6 of the glyph, which is why the band is six high:
\ *	rows 0 and 7 of every glyph in this font are blank.
\ *
\ *	Rolled up, bit 5 is row 0 and bit 0 is row 5. The bottom band
\ *	wants rows 0 downwards, so it takes the copy shifted up two and
\ *	ASLs; the top band is the 180-degree rotation and wants rows 5
\ *	upwards, so it LSRs the same byte. That is the whole of the
\ *	vertical flip - `zoom_mirror` does not survive into this port.

.ttl_cell
    lda ttl_bit
    bne ttl_c_shift
    jsr ttl_next_glyph
.ttl_c_shift
    inc ttl_bit
    lda ttl_bit
    and #7
    sta ttl_bit

    lda #0
    sta ttl_bits_t
    ldx #0
.ttl_c_row
    asl ttl_zbuf+1, x
    rol ttl_bits_t
    inx
    cpx #TTL_BAND_ROWS
    bne ttl_c_row

    lda ttl_bits_t
    asl a
    asl a
    sta ttl_bits_b
    rts

\ ******************************************************************
\ *	zm_write_band - one cell into all six rows of a band
\ ******************************************************************
\ *	write_ptr = the cell address for row 0, already inside the ring.
\ *	zm_bits holds the six bits and zm_shift is patched to ASL or LSR
\ *	to say which end of them this band reads from.
\ *
\ *	The +640 wraps at the top of the ring: the display's own 8K wrap
\ *	does the same thing to the address the CRTC is fetching, and the
\ *	two have to agree or the write lands where the picture is not.

.zm_write_band
    ldx #TTL_BAND_ROWS
.zm_row
.zm_shift
    asl zm_bits                 ; SELF-MODIFIED: LSR for the top band
    bcs zm_solid
    lda #LO(ttl_blank) : sta read_ptr
    lda #HI(ttl_blank) : sta read_ptr+1
    bne zm_draw                 ; a bank address: the high byte is never 0
.zm_solid
    lda #LO(ttl_block) : sta read_ptr
    lda #HI(ttl_block) : sta read_ptr+1
.zm_draw
    ldy #TTL_CELL-1
.zm_copy
    lda (read_ptr), y
    sta (write_ptr), y
    dey
    bpl zm_copy

    clc
    lda write_ptr   : adc #LO(row_stride) : sta write_ptr
    lda write_ptr+1 : adc #HI(row_stride)
    cmp #HI(TTL_RING + TTL_RING_SIZE)
    bcc zm_wrapped
    sbc #HI(TTL_RING_SIZE)
.zm_wrapped
    sta write_ptr+1
    dex
    bne zm_row
    rts

\ ******************************************************************
\ *	ttl_frame - one field of the titles page
\ ******************************************************************
\ *	Called straight after the VSync handler has returned, which is
\ *	where the two windows are. Each band's memory is fetched only
\ *	during its own cycle, so the top band - rows 5 to 10 - has to be
\ *	finished by row 5 and the bottom band - rows 19 to 24 - by row 19.
\ *	The top one goes first for that reason.
\ *
\ *	The ring pointers move under SEI because the IRQ reads them: the
\ *	top band's at fire 1, absolute row 2, and the bottom band's at
\ *	fire 4, absolute row 12.

.ttl_frame
    jsr ttl_cell

    \ ---- the top band: MAIN, and the picture rotated 180 degrees, so
    \ the window walks BACKWARDS and the new cell enters at the left.
    lda ttl_bits_t : sta zm_bits
    lda #&4e : sta zm_shift             ; LSR abs
    php : sei
    sec
    lda ttl_top   : sbc #TTL_CELL/8 : sta ttl_top
    lda ttl_top+1 : sbc #0
    cmp #HI(TTL_RING/8)
    bcs ttl_f_tok
    adc #HI(TTL_RING_SIZE/8)            ; carry is clear here
.ttl_f_tok
    sta ttl_top+1
    sta write_ptr+1
    lda ttl_top : sta write_ptr
    plp
    asl write_ptr : rol write_ptr+1     ; the CRTC unit is eight bytes
    asl write_ptr : rol write_ptr+1
    asl write_ptr : rol write_ptr+1
    lda &fe34
    and #&ff - 4                        ; X = 0: the CPU writes MAIN
    sta &fe34
    jsr zm_write_band

    \ ---- the bottom band: SHADOW, the message the right way up, the
    \ window walking forwards and the new cell entering at the right.
    lda ttl_bits_b : sta zm_bits
    lda #&0e : sta zm_shift             ; ASL abs
    php : sei
    clc
    lda ttl_bot   : adc #TTL_CELL/8 : sta ttl_bot
    lda ttl_bot+1 : adc #0
    cmp #HI((TTL_RING + TTL_RING_SIZE)/8)
    bcc ttl_f_bok
    sbc #HI(TTL_RING_SIZE/8)
.ttl_f_bok
    sta ttl_bot+1
    sta write_ptr+1
    lda ttl_bot : sta write_ptr
    plp
    asl write_ptr : rol write_ptr+1
    asl write_ptr : rol write_ptr+1
    asl write_ptr : rol write_ptr+1
    clc                                 ; the last cell of the row
    lda write_ptr   : adc #LO(row_stride - TTL_CELL) : sta write_ptr
    lda write_ptr+1 : adc #HI(row_stride - TTL_CELL)
    cmp #HI(TTL_RING + TTL_RING_SIZE)
    bcc ttl_f_bw
    sbc #HI(TTL_RING_SIZE)
.ttl_f_bw
    sta write_ptr+1
    lda &fe34
    ora #4                              ; X = 1: the CPU writes SHADOW
    sta &fe34
    jmp zm_write_band


\ ******************************************************************
\ *	The credits raster (Layer 6e, decisions 2 and 3 of the layer)
\ ******************************************************************
\ *	The C64's `ttl_pulse` is a HORIZONTAL colour-RAM cycle along the
\ *	first and last credit lines, running in opposite directions. MODE
\ *	2 has no colour RAM, so it cannot be transcribed; the CPC hit the
\ *	same wall and turned the effect through ninety degrees, and this
\ *	is `TitleRaster` ported - eight scanlines of palette writes per
\ *	line, the same list indexed from opposite ends.
\ *
\ *	The colours are the CPC's own `RasterPal`, decoded through the
\ *	Gate Array table and collapsed to MODE 2's eight by hue exactly as
\ *	decision 41 collapses the artwork. It is a heat pulse: the body
\ *	runs red, blue, bright red, purple, orange, pink, bright yellow,
\ *	pastel yellow, bright white and back down, and the trailing colour
\ *	follows four steps behind. Steps 9-15 are 7 down to 1, so sixteen
\ *	steps ping-pong over nine colours; the last eight repeat the first
\ *	eight so an eight-step window starting at step 15 can run off the
\ *	end, as the CPC's does.
\ *
\ *	The collapse doubles three of the nine steps - bright red and
\ *	orange land on red with plain red, pastel yellow on yellow with
\ *	bright yellow, pink on magenta with purple - so nine colours
\ *	become six. Faithful, and KC's eye has the last word on it.
\ *
\ *	Our credits are drawn in blue, cyan and white by export_title.py's
\ *	PAIR_COLOUR, and pair 3 - white, logical 7 - is the one the C64
\ *	pulses through colour RAM. So logical 7 takes the body list and
\ *	logical 6 the trailing one, and logical 4 is left as the shadow.
\ ******************************************************************

\ LOGICALS 15 AND 14, not 7 and 6: Layer 9e moved the credits' font onto
\ logicals 12, 14 and 15 so that they could be faded on the palette while
\ the panel and both zoom bands stay lit (decision 53). setup_display maps
\ 8-15 back onto 0-7, so the colours are the same ones - every byte here is
\ the old one plus &80, which is the logical nibble's top bit.
.ttl_pal
EQUB &f6, &e7, &f3, &e7, &f6, &e6, &f2, &e6
EQUB &f6, &e3, &f2, &e3, &f4, &e6, &f4, &e6
EQUB &f0, &e6, &f4, &e6, &f4, &e6, &f2, &e3
EQUB &f6, &e3, &f2, &e6, &f6, &e6, &f3, &e7
EQUB &f6, &e7, &f3, &e7, &f6, &e6, &f2, &e6
EQUB &f6, &e3, &f2, &e3, &f4, &e6, &f4, &e6

TTL_PAL_STEPS = 16              ; before the repeat; the window is eight long
TTL_RASTER_ROWS = 8             ; one character row

.ttl_pulse  EQUB 0              ; 0-31; one step every two fields, as the C64
.ttl_rcount EQUB 0

\ ******************************************************************
\ *	ttl_raster - one credit line's eight scanlines
\ ******************************************************************
\ *	X = the first step, as a byte offset into ttl_pal. Called from
\ *	inside the IRQ, so interrupts are already off and the only thing
\ *	that can move the timing is where the fire landed.
\ *
\ *	The loop is padded to one scanline. Every iteration starts with a
\ *	write to &FE21, which is on the 1 MHz bus, so the CPU stalls to
\ *	the same phase each time and the loop cannot drift by an odd
\ *	cycle - which is what makes a padded loop stable enough to do
\ *	this at all. TTL_RASTER_PAD is tuned by looking at the screen.

TTL_RASTER_PAD = 18

.ttl_raster
    lda ttl_fade_on             ; the credits are crossfading and the palette
    bne ttl_r_out               ; is theirs: putting 15 and 14 back to full
    lda #TTL_RASTER_ROWS
    sta ttl_rcount
.ttl_r_line
    lda ttl_pal, x
    sta VIDEO_ULA_PAL
    lda ttl_pal+1, x
    sta VIDEO_ULA_PAL
    inx
    inx
    ldy #TTL_RASTER_PAD
.ttl_r_pad
    dey
    bne ttl_r_pad
    dec ttl_rcount
    bne ttl_r_line

    \ and back to what setup_display set, before the panel sees it
    lda #&f0 + (7 EOR 7)                ; logical 15 -> white
    sta VIDEO_ULA_PAL
    lda #&e0 + (6 EOR 7)                ; logical 14 -> cyan
    sta VIDEO_ULA_PAL
.ttl_r_out
    rts

\ ******************************************************************
\ *	ttl_rupt_timer - the titles' four-cycle rupture
\ ******************************************************************
\ *	Called from rupt_timer in main RAM, which pages this bank in and
\ *	puts &F4's bank back afterwards. Here rather than in main RAM
\ *	because main RAM has 145 bytes and this is more than that.
\ *
\ *	  fire 1  abs  2  A row 2   R4 for A; R6 and R12/13 for B
\ *	  fire 2  abs  7  B row 2   R4 for B, which C inherits unchanged;
\ *	                            R6 and R12/13 for C
\ *	  fire 3  abs 11  B row 6   the display bank -> SHADOW. B's
\ *	                            seventh row is fetched by nobody, so
\ *	                            the write has a row of slack
\ *	  fire 4  abs 12  C row 0   R6 and R12/13 for D
\ *	  fire 5  abs 17  C row 5   (the second raster, when there is one)
\ *	  fire 6  abs 20  D row 1   R4 for D
\ *
\ *	R7 is a constant, as it is in the game: 15 is past the end of A,
\ *	B and C, and can only be reached in D.

.ttl_rupt_timer
    lda rupt_state
    bne ttl_rt_not1

    \ ---- fire 1: A row 2 ----
    CRTC 4, TTL_PANEL_R4                ; A's own
    CRTC 6, TTL_BAND_ROWS               ; for B
    lda #12 : sta CRTC_ADDR : lda ttl_top+1 : sta CRTC_DATA
    lda #13 : sta CRTC_ADDR : lda ttl_top   : sta CRTC_DATA
    lda #LO(TTL_T1_I3) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I3) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not1
    cmp #1
    bne ttl_rt_not2

    \ ---- fire 2: B row 2 ----
    CRTC 4, TTL_BAND_R4                 ; B's own, and C is the same shape
    CRTC 6, TTL_BAND_ROWS               ; for C
    CRTC 12, HI(TTL_CRED/8)
    CRTC 13, LO(TTL_CRED/8)
    lda #LO(TTL_T1_I4) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I4) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not2
    cmp #2
    bne ttl_rt_not3

    \ ---- fire 3: B row 6, the blank one ----
    lda &fe34
    ora #1                              ; D = 1: display SHADOW for C and D
    sta &fe34
    lda #LO(TTL_T1_I5) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I5) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not3
    cmp #3
    bne ttl_rt_not4

    \ ---- fire 4: C row 0, the first credit line ----
    \ The raster FIRST: it has to start on the row's first scanline, and
    \ D's registers only have to be written some time inside C, which
    \ runs to absolute row 18.
    lda ttl_pulse
    and #TTL_PAL_STEPS * 2 - 2          ; the CPC's own AND &1E
    tax
    jsr ttl_raster
    CRTC 6, TTL_BAND_ROWS               ; for D
    lda #12 : sta CRTC_ADDR : lda ttl_bot+1 : sta CRTC_DATA
    lda #13 : sta CRTC_ADDR : lda ttl_bot   : sta CRTC_DATA
    lda #LO(TTL_T1_I6) : sta SYS_VIA_T1LL
    lda #HI(TTL_T1_I6) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not4
    cmp #4
    bne ttl_rt_not5

    \ ---- fire 5: C row 5, the last credit line ----
    \ Indexed from the other end of the list, which is the CPC's own
    \ neg / add 30, and is what makes the two lines run opposite ways -
    \ as the C64's two colour-RAM lines do.
    lda ttl_pulse
    and #TTL_PAL_STEPS * 2 - 2
    sta ttl_rcount
    lda #TTL_PAL_STEPS * 2 - 2
    sec
    sbc ttl_rcount
    tax
    jsr ttl_raster
    lda #LO(T1_I3) : sta SYS_VIA_T1LL   ; the long dummy: VSync restarts T1
    lda #HI(T1_I3) : sta SYS_VIA_T1LH
    inc rupt_state
    rts

.ttl_rt_not5
    cmp #5
    bne ttl_rt_done

    \ ---- fire 6: D row 1 ----
    \ R4 has to be written inside its own cycle, and D is the only cycle
    \ this can be done from - see the note in main.asm.
    CRTC 4, TTL_LAST_R4
    inc rupt_state

    \ and the pulse on a step, one every two fields as ttl_pulse_tmr does
    inc ttl_pulse
    lda ttl_pulse
    and #TTL_PAL_STEPS * 2 - 1
    sta ttl_pulse
.ttl_rt_done
    rts

\ ******************************************************************
\ *	expl_dirs_load - the player's six pieces get their vectors
\ ******************************************************************
\ *	The C64's second loop in life_lost_init, and the table it reads.
\ *	Up here because main RAM has no room BELOW SPR_SAVE for a table
\ *	read at runtime, and that is the only room that counts: the
\ *	vectors had drifted to &2024, inside the blitter's save area for
\ *	sprite slot 0, so the player's own saved background was landing
\ *	on the numbers his pieces were about to fly on. The pieces then
\ *	inherited zero for both movement commands and sat where he died.
\ *
\ *	The original's table is sixteen bytes and life_lost reads from
\ *	+2*ENEMY_FIRST; the first four are the player's and the bullet's
\ *	slots, which have no pieces to throw, so only the twelve that are
\ *	read are here. Movement commands in emove's encoding, one pair a
\ *	pool slot, values verbatim.
\ ******************************************************************

.explosion_dirs
EQUB &19, &09, &44, &44, &22, &22
EQUB &8a, &8a, &45, &45, &26, &26

.expl_dirs_load
{
    ldx #0
    .loop
    lda explosion_dirs, x
    sta enemy_spds+2*ENEMY_FIRST, x
    inx
    cpx #2*ENEMY_COUNT
    bne loop
    rts
}

\ ---- the starfield's tables (Layer 9c) --------------------------
\ Down here, ahead of the tune's stream, because this is the only
\ hole they fit in and the code they belong to is past it. The
\ commentary is with the code.
\ The CPC's ten, from the StarsLow table in Compiled_Main3.asm. Its
\ offsets decode to scanline 0 of alternating character rows at these
\ byte columns; its screen is 80 bytes across and 20 rows tall in the
\ play area, which is ours exactly, so they transcribe unaltered. The
\ order is the CPC's, and it matters: the first five take one colour
\ and the last five the other, which is what puts alternating rows in
\ alternating colours - and now in alternating speeds with them.
STAR_ROW_0 =  1 : STAR_COL_0 = 62
STAR_ROW_1 =  5 : STAR_COL_1 = 38
STAR_ROW_2 =  9 : STAR_COL_2 = 58
STAR_ROW_3 = 13 : STAR_COL_3 = 18
STAR_ROW_4 = 17 : STAR_COL_4 = 10
STAR_ROW_5 =  3 : STAR_COL_5 =  8
STAR_ROW_6 =  7 : STAR_COL_6 = 28
STAR_ROW_7 = 11 : STAR_COL_7 = 66
STAR_ROW_8 = 15 : STAR_COL_8 = 44
STAR_ROW_9 = 19 : STAR_COL_9 = 56

\ Screen offset of a star's byte: the origin of the picture is
\ corner_addr + 8, as sprite.asm has it, and the star sits on scanline
\ 0 of its character row. Written out rather than through a macro -
\ beebasm will not take a macro name beginning with a mnemonic, and
\ every name for this one begins with STA.
.star_ofs0_lo
EQUB LO(8 + STAR_ROW_0*row_stride + STAR_COL_0*8), LO(8 + STAR_ROW_1*row_stride + STAR_COL_1*8)
EQUB LO(8 + STAR_ROW_2*row_stride + STAR_COL_2*8), LO(8 + STAR_ROW_3*row_stride + STAR_COL_3*8)
EQUB LO(8 + STAR_ROW_4*row_stride + STAR_COL_4*8), LO(8 + STAR_ROW_5*row_stride + STAR_COL_5*8)
EQUB LO(8 + STAR_ROW_6*row_stride + STAR_COL_6*8), LO(8 + STAR_ROW_7*row_stride + STAR_COL_7*8)
EQUB LO(8 + STAR_ROW_8*row_stride + STAR_COL_8*8), LO(8 + STAR_ROW_9*row_stride + STAR_COL_9*8)
.star_ofs0_hi
EQUB HI(8 + STAR_ROW_0*row_stride + STAR_COL_0*8), HI(8 + STAR_ROW_1*row_stride + STAR_COL_1*8)
EQUB HI(8 + STAR_ROW_2*row_stride + STAR_COL_2*8), HI(8 + STAR_ROW_3*row_stride + STAR_COL_3*8)
EQUB HI(8 + STAR_ROW_4*row_stride + STAR_COL_4*8), HI(8 + STAR_ROW_5*row_stride + STAR_COL_5*8)
EQUB HI(8 + STAR_ROW_6*row_stride + STAR_COL_6*8), HI(8 + STAR_ROW_7*row_stride + STAR_COL_7*8)
EQUB HI(8 + STAR_ROW_8*row_stride + STAR_COL_8*8), HI(8 + STAR_ROW_9*row_stride + STAR_COL_9*8)
.star_col0
EQUB STAR_COL_0, STAR_COL_1, STAR_COL_2, STAR_COL_3, STAR_COL_4
EQUB STAR_COL_5, STAR_COL_6, STAR_COL_7, STAR_COL_8, STAR_COL_9

\ The CPC's two pens, 10 and 4 of the in-game Mode0Pal read reversed
\ (decision 41): cyan and green. One MODE 2 fat pixel each, and they
\ start in the LEFT half of the byte - logical 6 is &28 and logical 2
\ is &08. Both are non-zero, which the blank test relies on.
STAR_CYAN  = &28
STAR_GREEN = &08
.star_pix0
EQUB STAR_CYAN,  STAR_CYAN,  STAR_CYAN,  STAR_CYAN,  STAR_CYAN
EQUB STAR_GREEN, STAR_GREEN, STAR_GREEN, STAR_GREEN, STAR_GREEN

\ How often a star steps a pixel: `frame_count AND mask` = 0. The level
\ moves a pixel every frame, so 1 is half its speed and 3 a quarter.
\ Cyan is the nearer plane and green the further one, and because the
\ two sets alternate rows the depth alternates with them.
STAR_NEAR = 1
STAR_FAR  = 3
.star_mask
EQUB STAR_NEAR, STAR_NEAR, STAR_NEAR, STAR_NEAR, STAR_NEAR
EQUB STAR_FAR,  STAR_FAR,  STAR_FAR,  STAR_FAR,  STAR_FAR


\ ---- the "mega hero" message's data (Layer 9c) ------------------
\ In the same hole as the starfield's tables, and for the same reason:
\ 171 bytes were left between them and the tune's B1 stream at &B900,
\ and the code that reads this is past it. The commentary is with the
\ code, at the end of the bank.
MEGA_ROW_1 = 3                  ; the C64's screen row 8, and its row 16: our
MEGA_ROW_2 = 11                 ; play area is its rows 5-24, so both come
MEGA_CELLS = 240                ; down five. Six rows of forty cells.
MEGA_LAG   = 41                 ; the shadow: one row down, one cell right
MEGA_O1    = 8 + MEGA_ROW_1 * row_stride
MEGA_O2    = 8 + MEGA_ROW_2 * row_stride + (MEGA_CELLS - 1) * TTL_CELL
MEGA_SHADE = MEGA_LAG * TTL_CELL

.mega_data
IF GFX_CPC
INCBIN "src/data/mega-cpc.bin"
ELSE
INCBIN "src/data/mega.bin"
ENDIF
mega_block = mega_data          ; character $80, one 16-byte cell
mega_key   = mega_data + 16     ; which of its bytes the "is a letter here
                                ; already?" test compares - the first that is
                                ; not blank, so the answer stays meaningful
                                ; when the artwork does not have ink in byte 0
mega_bits1 = mega_data + 17     ; "MEGA", 240 bits, bit 7 the first cell
mega_bits2 = mega_data + 47     ; "HERO", stored back to front

\ The only table it has: may block 2's shadow blank a cell that already
\ carries a letter? Indexed by 0 for block 1 and 2 for block 2, as the
\ rest of its state is - and the rest of its state is in the &0800 block
\ in main RAM, because this bank has tens of bytes left and that has
\ hundreds.
.mega_gd    EQUB 0 : EQUB 0 : EQUB &ff


\ ******************************************************************
\ *	mega_one - one block's cell for this field. A = 0 or 2.
\ ******************************************************************

.mega_one
{
    sta mega_b
    tax
    asl mega_m, x               ; this cell's bit, out of the top
    bcc done

    lda mega_o, x   : sta mega_ofs
    lda mega_o+1, x : sta mega_ofs+1
    lda #LO(mega_block) : sta mega_src
    lda #HI(mega_block) : sta mega_src+1
    lda #0
    sta mega_guard
    jsr mega_plot

    clc                         ; and the shadow, MEGA_LAG cells on
    lda mega_ofs   : adc #LO(MEGA_SHADE) : sta mega_ofs
    lda mega_ofs+1 : adc #HI(MEGA_SHADE) : sta mega_ofs+1
    lda #LO(ttl_blank) : sta mega_src
    lda #HI(ttl_blank) : sta mega_src+1
    ldx mega_b
    lda mega_gd, x
    sta mega_guard
    jsr mega_plot
    .done
    rts
}

IF MUSIC_AKL = 0
\ The tune's B1 streams (decision 48). Nothing in this bank reads them:
\ they are here because the .vgi's eleven register streams do not have to be
\ in one place, and the tail of a sprite bank is a place. lib/vgiplayer.asm
\ pages this bank in for the byte and out again.
PRINT "BANK 1 HOLE BELOW THE TUNE =", ~MUSIC_B1_BASE - P%
ASSERT P% <= MUSIC_B1_BASE
CLEAR MUSIC_B1_BASE, &C000
ORG MUSIC_B1_BASE
.music_b1
INCBIN "src/data/music_b1.bin"
.music_b1_end
ASSERT music_b1_end <= &C000
ENDIF

\ ******************************************************************
\ *	Layer 9c: the parallax starfield
\ ******************************************************************
\ *	Ten stars on scanline 0 of every other character row, drifting
\ *	left more slowly than the level does, at two speeds. Five go at
\ *	half the scroll and five at a quarter, and the two sets alternate
\ *	rows, so the play area reads as three planes: the scenery in
\ *	front, then the cyan stars, then the green.
\ *
\ *	THE TEN, AND THE RULES, ARE THE CPC PORT'S, NOT THE C64'S. The
\ *	original animates a single pixel in row 0 of character $FF
\ *	(`star_decode`, `sta $47f8` in rout2) - and character $FF is in
\ *	neither `tiles.til` nor the map, so nothing ever displays it. The
\ *	only $FF on its screen is the status bar's last row, whose colour
\ *	RAM is $00: black on black. The C64's starfield is dead code.
\ *	Axelay's CPC port wrote a real one
\ *	(source_cpc/Source/EG_Stars3.asm) and this is that: its ten
\ *	positions, its two colours, and its two rules.
\ *
\ *	THE TWO RULES ARE WHAT MAKE IT CHEAP. A star is plotted only into
\ *	a byte that is blank, so it never covers the scenery and never has
\ *	to remember what it covered; and it is wiped by writing that blank
\ *	back. So the only thing worth remembering is WHERE, which is
\ *	star_lo/star_hi - per bank, because a bank is redrawn every other
\ *	frame and what has to be put back is wherever that bank last left
\ *	it. A zero high byte means this bank did not plot this star at
\ *	all, and no address in a play buffer has one.
\ *
\ *	THE DRIFT IS OURS (decision 51). The CPC's stars stand still on
\ *	the screen; ours step one fat pixel left on their own beat, which
\ *	is `frame_count AND star_mask`. The level moves one fat pixel a
\ *	frame, so mask 1 is half its speed and mask 3 a quarter, and
\ *	everything is slower than the scenery - which is the whole point:
\ *	nearer things move faster, so a star that moves at all has to
\ *	move less than the level in front of it.
\ *
\ *	A step is half a byte. Moving left out of the LEFT half of a byte
\ *	lands in the RIGHT half of the byte before it, so the pixel goes
\ *	down a shift and the column goes back one; moving left out of the
\ *	right half lands in the left half of the same byte, so only the
\ *	pixel moves. MODE 2 puts the left pixel's four bits at 7,5,3,1 and
\ *	the right pixel's at 6,4,2,0, so the two forms are one ASL apart
\ *	and `AND #&55` tells them apart.
\ *
\ *	WHY IT NEEDS NO ADDRESS OF ITS OWN. The CPC increments each star's
\ *	screen address every frame to cancel the scroll. We do not have
\ *	to: `corner_addr` already is that address. A star is a sprite that
\ *	never moves except when we move it, and `sprite.asm` places one at
\ *	`corner_addr + 8 + row * 640 + column * 8`; `scroll_advance`
\ *	running AFTER the draw is what makes a stationary sprite
\ *	stationary (BUGS.md #7). So star_ofs is a screen offset, the same
\ *	in both banks, and the drift is the only thing that changes it.
\ *
\ *	The two banks hold the same picture one pixel apart, so a star at
\ *	the same byte and the same half-byte in both is at the same screen
\ *	pixel in both, and does not shimmer. Only the blank test can
\ *	disagree between them, at the edge of a piece of scenery.
\ *
\ *	A star may stand in the incoming column, 79, and one will: they
\ *	visit every column now. That is safe only because `scroll_frame`
\ *	runs BEFORE this does, so the star goes on top of a column that
\ *	has just been written, and by the time this bank comes round again
\ *	the scroll has moved on and nothing has repainted it.
\ *
\ *	NOT PORTED: the CPC swaps its two colours over every second frame,
\ *	to hide a half-character R3 shift on monitors that do not do it
\ *	cleanly. We have no R3 and no shift, and at 25 Hz the swap would
\ *	be a visible flicker rather than a disguise.
\ *
\ *	Here in bank 1 because main RAM has 185 bytes and this is more
\ *	than half of them, and because the 247 bytes between the zoom
\ *	scroller and the tune's B1 stream at &B900 were dead space.
\ *	Reached through bank_call, like the zoom scroller above it. It
\ *	reads `corner_addr` and `frame_count` in zero page and writes the
\ *	play buffer, none of which is paged, so being up here costs it
\ *	nothing but the call.
\ ******************************************************************

\ ******************************************************************
\ *	star_init - back to the CPC's positions, nothing on screen
\ ******************************************************************
.star_init
{
    ldx #STAR_COUNT-1
    .loop
    lda star_ofs0_lo, x
    sta star_ofs_lo, x
    lda star_ofs0_hi, x
    sta star_ofs_hi, x
    lda star_col0, x
    sta star_col, x
    lda star_pix0, x
    sta star_pix, x
    dex
    bpl loop

    lda #0
    ldx #STAR_BANK + STAR_COUNT - 1
    .clear
    sta star_hi, x              ; star_lo needs no clearing: this gates it
    dex
    bpl clear
    rts
}

\ ******************************************************************
\ *	star_frame - put last time's stars back, drift, plot this time's
\ ******************************************************************
\ *	X walks the star and Y the same star in the bank being drawn,
\ *	which is why the screen byte is reached through self-modified
\ *	absolute addresses rather than (zp),Y: it leaves both index
\ *	registers to the loop.
\ ******************************************************************

.star_frame
{
    lda &fe34
    and #4                      ; the X bit: the bank the CPU is drawing
    asl a
    asl a                       ; 0 for main, STAR_BANK for shadow
    clc
    adc #STAR_COUNT-1
    tay
    ldx #STAR_COUNT-1

    .loop

    \\ ---- put the blank back where this bank last drew this star ---
    lda star_hi, y
    beq not_drawn
    sta wipe+2
    lda star_lo, y
    sta wipe+1
    lda #0
    sta star_hi, y
    .wipe
    sta &ffff
    .not_drawn

    \\ ---- drift one fat pixel left, on this star's own beat --------
    lda frame_count
    and star_mask, x
    bne no_step

    lda star_pix, x
    and #&55                    ; bits in the right-hand pixel?
    bne to_left

    \\ Out of the left half of this byte, into the right half of the
    \\ one before it: down a shift, and back a column.
    lsr star_pix, x
    dec star_col, x
    bpl back_one
    lda #PLAY_COLS-1            ; off the left edge and on again at the right
    sta star_col, x
    clc
    lda star_ofs_lo, x
    adc #LO(PLAY_COLS * 8 - 8)
    sta star_ofs_lo, x
    lda star_ofs_hi, x
    adc #HI(PLAY_COLS * 8 - 8)
    sta star_ofs_hi, x
    jmp no_step

    .back_one
    sec
    lda star_ofs_lo, x
    sbc #8
    sta star_ofs_lo, x
    lda star_ofs_hi, x
    sbc #0
    sta star_ofs_hi, x
    jmp no_step

    \\ Out of the right half into the left half of the same byte: the
    \\ pixel moves and the column does not.
    .to_left
    asl star_pix, x

    .no_step

    \\ ---- where it is now, in the bank being drawn -----------------
    \\ The buffer is 16K and hardware-wrapped, and corner_addr plus an
    \\ offset can only pass &8000 once, so one subtraction puts it back.
    clc
    lda corner_addr
    adc star_ofs_lo, x
    sta test+1
    sta plot+1
    lda corner_addr+1
    adc star_ofs_hi, x
    cmp #HI(screen_top)
    bcc in_range
    sbc #HI(screen_size)
    .in_range
    sta test+2
    sta plot+2

    \\ ---- plot, but only into scenery that is not there ------------
    .test
    lda &ffff
    bne blocked
    lda star_pix, x
    .plot
    sta &ffff
    lda plot+1                  ; and remember it, for this bank's next wipe
    sta star_lo, y
    lda plot+2
    sta star_hi, y
    .blocked

    dey
    dex
    bmi done                    \ the body is past a branch's reach from the top
    jmp loop
    .done
    rts
}

\ ******************************************************************
\ *	Layer 9c: the completion sequence's "MEGA HERO" message
\ ******************************************************************
\ *	The C64's comp_mess draws it a cell a field over the frozen play
\ *	area: character $80 in light green wherever mega_hero_txt holds
\ *	$20 - six rows of forty at screen row 8, and the same again at row
\ *	16 revealed from its LAST cell backwards, so the two blocks meet
\ *	in the middle. It is not a font and never needed one: it is two
\ *	240-cell on/off bitmaps and one repeated character, which is what
\ *	docs/layer-6c-state-machine.md corrected on 2026-09-04.
\ *
\ *	A C64 character is four multicolour pixels, so it is four of our
\ *	fat pixels, so forty of them are our whole 160-pixel width and one
\ *	cell is 16 bytes - the zoom scroller's cell exactly, and copied the
\ *	same way. tools/export_mega.py converts the character and both
\ *	bitmaps; the second is stored back to front, so one ASL a step
\ *	serves a block that reveals forwards and a block that reveals back.
\ *
\ *	THE SHADOW IS THE ORIGINAL'S. Beside every cell it draws, the C64
\ *	blanks the cell 41 on - one row down and one to the right - which
\ *	punches the scenery out behind the letters and leaves them a drop
\ *	shadow. Block 1 runs forwards, so the cell it blanks cannot have
\ *	been drawn yet and needs no test; block 2 runs backwards, so the
\ *	cell it blanks may already carry a letter, and the original reads
\ *	the screen to find out before it blanks. Both transcribe.
\ *
\ *	IT BLOCKS, and the whole loop is up here, because comp_mess in
\ *	bank 0 has twenty-five bytes left and this is two hundred. Nothing
\ *	in a sideways bank may call main RAM - but field_wait is three
\ *	instructions over a main-RAM variable and inlines, and for the five
\ *	seconds this takes nothing runs but the music interrupt.
\ *
\ *	BOTH BANKS, every cell. field_wait hands no frame over, so the
\ *	display stands still on one bank while this runs - but the finale
\ *	after it flips again, and a message in one bank only would strobe
\ *	at 25 Hz from the moment it did.
\ ******************************************************************


\ ******************************************************************
\ *	mega_mess - the message, a cell a field, and then return
\ ******************************************************************

.mega_mess
{
    lda #LO(MEGA_O1) : sta mega_o
    lda #HI(MEGA_O1) : sta mega_o+1
    lda #LO(MEGA_O2) : sta mega_o+2
    lda #HI(MEGA_O2) : sta mega_o+3
    lda #0
    sta mega_j

    .group
    ldx mega_j
    lda mega_bits1, x
    sta mega_m
    lda mega_bits2, x
    sta mega_m+2
    inc mega_j
    lda #8
    sta mega_n

    .cell
    \ field_wait, inlined: it is a read of a main-RAM variable and
    \ nothing more, and this bank cannot call the routine itself.
    lda field_count
    .same
    cmp field_count
    beq same

    lda #0
    jsr mega_one
    lda #2
    jsr mega_one

    clc                         ; block 1 forwards, block 2 backwards
    lda mega_o   : adc #TTL_CELL : sta mega_o
    lda mega_o+1 : adc #0        : sta mega_o+1
    sec
    lda mega_o+2 : sbc #TTL_CELL : sta mega_o+2
    lda mega_o+3 : sbc #0        : sta mega_o+3

    dec mega_n
    bne cell
    lda mega_j
    cmp #MEGA_CELLS / 8
    bne group
    rts
}


\ ******************************************************************
\ *	mega_plot - one cell into BOTH banks
\ ******************************************************************
\ *	mega_ofs is the offset from corner_addr, mega_src the sixteen
\ *	bytes to put there, and mega_guard says whether a cell already
\ *	carrying a letter is to be left alone. Two byte columns of eight
\ *	rather than one run of sixteen: the buffer wraps at 16K and a
\ *	sixteen-byte run can straddle the wrap, but an eight-byte column
\ *	starting on an eight-byte boundary cannot.
\ ******************************************************************

.mega_plot
{
    lda &fe34
    pha
    and #255 - 4                ; the CPU sees MAIN
    jsr pass
    lda &fe34
    ora #4                      ; and then SHADOW
    jsr pass
    pla
    sta &fe34
    rts

    .pass
    sta &fe34
    ldx #0
    jsr ptrs
    lda mega_guard
    beq columns
    ldy mega_key
    lda (write_ptr), y
    cmp mega_block, y
    beq out                     ; a letter is there already: leave it alone
    .columns
    jsr copy8
    ldx #8
    jsr ptrs
    jsr copy8
    .out
    rts

    \ X = the byte column within the cell, 0 or 8.
    .ptrs
    clc
    lda corner_addr
    adc mega_ofs
    sta write_ptr
    lda corner_addr+1
    adc mega_ofs+1
    sta write_ptr+1
    txa
    clc
    adc write_ptr
    sta write_ptr
    bcc no_carry
    inc write_ptr+1
    .no_carry
    lda write_ptr+1
    cmp #HI(screen_top)
    bcc in_range
    sbc #HI(screen_size)
    sta write_ptr+1
    .in_range
    txa
    clc
    adc mega_src
    sta read_ptr
    lda mega_src+1
    adc #0
    sta read_ptr+1
    rts

    .copy8
    ldy #7
    .cl
    lda (read_ptr), y
    sta (write_ptr), y
    dey
    bpl cl
    rts
}


.bank1_end

SAVE "BANK1", bank1_start, bank1_end

PRINT "------"
PRINT "BANK 1 - sprites, shift 0, and the titles' zoom scroller"
PRINT "------"
PRINT "DATA size =",~bank1_end-bank1_start
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~&C000-P%
PRINT "------"
