\ ******************************************************************
\ *	bank3.asm
\ *	Sideways RAM bank 3 (slot SWRAM_COMPILED): straight-line 6502 for
\ *	the frames worth compiling (decision 29). Generated by
\ *	tools/compile_sprites.py; regenerate with the tool rather than
\ *	editing src/data.
\ *
\ *	A compiled body reads no sprite data - every pixel is an immediate -
\ *	so it does not belong to either pixel shift and both live here
\ *	together. That also gives the restore one bank to page in and
\ *	nothing to remember about which shift drew the sprite.
\ *
\ *	&8000  descriptors, four bytes a frame: draw lo/hi, restore lo/hi.
\ *	       spr_comp_lo/hi in the sprite banks point at these.
\ *	&8200  the bodies.
\ ******************************************************************

CLEAR 0,&FFFF
ORG &8000
GUARD &C000
.bank3_start

.compiled_data
INCBIN "src/data/compiled.bin"

\ ******************************************************************
\ *	The titles page's font and credits, and the code that draws them
\ ******************************************************************
\ *	Here rather than in bank 0 because bank 0 has 358 bytes left and
\ *	this is 702 of data, and because the page is drawn once: paging
\ *	this bank in for it costs nothing. tools/export_title.py.
\ *
\ *	The font is the C64's own status charset read as MULTICOLOUR, which
\ *	is what it is: four double-width pixels a character, which is one
\ *	of our 4-fat-pixel cells exactly, so the original's 38-column
\ *	layout lands at 1:1 with no rescaling.
\ *
\ *	CALLED THROUGH bank3_call IN MAIN RAM, which does the paging.
\ *	Nothing in this bank can page its own bank out.
\ ******************************************************************

TITLE_GLYPH_BYTES = 16
TITLE_LINE_LEN = 38
TITLE_LINES = 5

.title_font
INCBIN "src/data/title.bin"
title_lines_data = title_font + 32 * TITLE_GLYPH_BYTES

\ The C64 puts its five lines on screen rows 12, 14, 15, 16 and 17 of 25.
\ Ours is a 20-row play area under the panel, so they sit at 8, 10, 11, 12
\ and 13: the original's gaps kept, the block centred in the shorter area.
.title_rows EQUB 8, 10, 11, 12, 13

\ 38 characters is 152 of the 160 pixels, so one byte column of margin.
TITLE_COL0 = 2

\ The zero page it borrows: write_ptr and read_ptr are the generic pair, and
\ spr_tmp is the sprite engine's scratch. Nothing is drawing sprites while the
\ titles are up, and clear_play has finished with write_ptr before this runs.
.title_text
{
    ldx #0                      \\ line
    .line_loop
    stx line_no

    \\ write_ptr = screen_start + row * 640 + TITLE_COL0 * 8
    ldy title_rows, x
    lda #LO(screen_start + TITLE_COL0 * 8)
    sta write_ptr
    lda #HI(screen_start + TITLE_COL0 * 8)
    sta write_ptr+1
    .row_loop
    cpy #0
    beq row_done
    clc
    lda write_ptr   : adc #LO(row_stride) : sta write_ptr
    lda write_ptr+1 : adc #HI(row_stride) : sta write_ptr+1
    dey
    bne row_loop
    .row_done

    \\ read_ptr = this line's 38 glyph numbers. Four lines at 38 is 152,
    \\ so the multiply stays inside a byte.
    ldy #0
    .times_loop
    cpx #0
    beq times_done
    tya : clc : adc #TITLE_LINE_LEN : tay
    dex
    bne times_loop
    .times_done
    tya
    clc
    adc #LO(title_lines_data) : sta read_ptr
    lda #0
    adc #HI(title_lines_data) : sta read_ptr+1

    ldx #0
    .char_loop
    stx char_no

    \\ spr_tmp = title_font + glyph * 16. Thirty-two glyphs reach 496, so
    \\ the shift is a 16-bit one - a single ROL would lose the top bits.
    ldy #0
    lda (read_ptr), y
    sta spr_tmp
    lda #0
    sta spr_tmp+1
    ldx #4
    .shift
    asl spr_tmp
    rol spr_tmp+1
    dex
    bne shift
    clc
    lda spr_tmp   : adc #LO(title_font) : sta spr_tmp
    lda spr_tmp+1 : adc #HI(title_font) : sta spr_tmp+1

    \\ A glyph is two byte columns, and our byte columns are 8 bytes apart
    \\ and consecutive, so it is one straight 16-byte copy.
    ldy #TITLE_GLYPH_BYTES-1
    .copy
    lda (spr_tmp), y
    sta (write_ptr), y
    dey
    bpl copy

    clc
    lda write_ptr : adc #TITLE_GLYPH_BYTES : sta write_ptr
    bcc no_carry
    inc write_ptr+1
    .no_carry
    inc read_ptr
    bne no_carry2
    inc read_ptr+1
    .no_carry2

    ldx char_no
    inx
    cpx #TITLE_LINE_LEN
    bne char_loop

    ldx line_no
    inx
    cpx #TITLE_LINES
    beq done
    jmp line_loop
    .done
    rts

    .line_no EQUB 0
    .char_no EQUB 0
}

\ ******************************************************************
\ *	The status panel and the HUD (Layer 6d)
\ ******************************************************************
\ *	The C64's status bar is five rows of 40 characters assembled
\ *	straight into its screen buffer and never redrawn; only the score,
\ *	the high score and the lives bars move, and status_decode pokes
\ *	those characters back. tools/export_panel.py renders the whole
\ *	thing to MODE 2 once, at 1:1 - the charset is multicolour, so a
\ *	character is four double-width pixels, which is one of our
\ *	4-fat-pixel cells (decision 34 for the colour mapping).
\ *
\ *	Here in bank 3 because that is where the room is: main RAM has 36
\ *	bytes below &2000 and bank 0 has 151. Both routines are reached
\ *	through bank3_call in main RAM.
\ ******************************************************************

HUD_GLYPH_BYTES = 16
HUD_CELLS = 18                  ; 6 score + 6 high score + 6 lives

.panel_image
INCBIN "src/data/panel.bin"

.hud_glyphs
INCBIN "src/data/hud.bin"

\ The C64's status_decode writes the score to buffer_1+$02e, the high score
\ to +$042 and the lives bars to +$060: row 1 columns 6 and 26, row 2 column
\ 16. A cell is SIXTEEN bytes - four fat pixels is two byte columns, and a
\ byte column is eight - so it sits at PANEL_ADDR + row*640 + column*16, and
\ 40 of them is the 640-byte row exactly.
.hud_cell_lo
FOR c, 6, 11, 1
    EQUB LO(PANEL_ADDR + 1*row_stride + c*HUD_GLYPH_BYTES)
NEXT
FOR c, 26, 31, 1
    EQUB LO(PANEL_ADDR + 1*row_stride + c*HUD_GLYPH_BYTES)
NEXT
FOR c, 16, 21, 1
    EQUB LO(PANEL_ADDR + 2*row_stride + c*HUD_GLYPH_BYTES)
NEXT

.hud_cell_hi
FOR c, 6, 11, 1
    EQUB HI(PANEL_ADDR + 1*row_stride + c*HUD_GLYPH_BYTES)
NEXT
FOR c, 26, 31, 1
    EQUB HI(PANEL_ADDR + 1*row_stride + c*HUD_GLYPH_BYTES)
NEXT
FOR c, 16, 21, 1
    EQUB HI(PANEL_ADDR + 2*row_stride + c*HUD_GLYPH_BYTES)
NEXT

\ The C64's lives_display, as glyph indices: $00 -> 0, $8f -> 11, $90 -> 12.
\ Its rows are eight bytes and it uses six of them; ours are six.
.hud_lives
    EQUB  0,  0,  0,  0,  0,  0     ; no lives left
    EQUB  0,  0, 11, 12,  0,  0
    EQUB  0, 11, 12, 11, 12,  0
    EQUB 11, 12, 11, 12, 11, 12
.hud_lives_off EQUB 0, 6, 12, 18

\ What the panel should show, and what each bank's panel is already
\ showing. A bank is redrawn every other game frame, so the two are
\ tracked apart, exactly as the sprite engine tracks its save state:
\ a change writes into the bank the CPU owns now and again next frame.
.hud_want SKIP HUD_CELLS
.hud_have SKIP 2 * HUD_CELLS

\ ******************************************************************
\ *	panel_draw - the panel image into the bank the CPU owns
\ ******************************************************************
\ *	Called once per bank at boot, from panel_init in bank 0 through
\ *	bank3_call. 3200 bytes is 12 whole pages and 128.
\ ******************************************************************

.panel_draw
{
    lda #LO(panel_image)  : sta read_ptr
    lda #HI(panel_image)  : sta read_ptr+1
    lda #LO(PANEL_ADDR)   : sta write_ptr
    lda #HI(PANEL_ADDR)   : sta write_ptr+1

    ldx #HI(PANEL_BYTES)
    ldy #0
    .page
    lda (read_ptr), y
    sta (write_ptr), y
    iny
    bne page
    inc read_ptr+1
    inc write_ptr+1
    dex
    bne page
    .tail
    lda (read_ptr), y
    sta (write_ptr), y
    iny
    cpy #LO(PANEL_BYTES)
    bne tail

    \\ Nothing of the HUD survives a repaint, in either bank.
    ldx #2*HUD_CELLS-1
    lda #&ff
    .dirty
    sta hud_have, x
    dex
    bpl dirty
    rts
}

\ ******************************************************************
\ *	status_decode - the C64's, once a game frame
\ ******************************************************************
\ *	The original runs this from its raster interrupt every field and
\ *	writes all eighteen characters every time, because a character is
\ *	one byte there. Ours is sixteen, in two banks, so it writes only
\ *	the cells that have changed since this bank was last painted -
\ *	typically one or two digits, and nothing at all on a still frame.
\ ******************************************************************

.status_decode
{
    \\ ---- what the panel should show -------------------------------
    ldx lives
    cpx #4
    bcc lives_ok
    ldx #3                      ; never happens; costs four cycles to be sure
    .lives_ok
    ldy hud_lives_off, x

    ldx #0
    .want_loop
    lda score, x
    clc
    adc #1                      ; glyph 1 is '0'; the C64 adds $21 for the same
    sta hud_want, x
    lda hi_score, x
    clc
    adc #1
    sta hud_want + 6, x
    lda hud_lives, y
    sta hud_want + 12, x
    iny
    inx
    cpx #SCORE_DIGITS
    bne want_loop

    \\ ---- and what this bank is showing ----------------------------
    lda &fe34
    and #4                      ; X bit: the bank the CPU writes
    beq main_bank
    lda #HUD_CELLS
    .main_bank
    sta bank_off

    ldx #0
    .cell_loop
    txa
    clc
    adc bank_off
    tay
    lda hud_want, x
    cmp hud_have, y
    beq next_cell
    sta hud_have, y

    \\ read_ptr = hud_glyphs + glyph * 16. Thirteen glyphs reach 192, so
    \\ the shift stays inside a byte.
    asl a : asl a : asl a : asl a
    clc
    adc #LO(hud_glyphs) : sta read_ptr
    lda #0
    adc #HI(hud_glyphs) : sta read_ptr+1

    lda hud_cell_lo, x : sta write_ptr
    lda hud_cell_hi, x : sta write_ptr+1

    ldy #HUD_GLYPH_BYTES-1
    .copy
    lda (read_ptr), y
    sta (write_ptr), y
    dey
    bpl copy

    .next_cell
    inx
    cpx #HUD_CELLS
    bne cell_loop
    rts

    .bank_off EQUB 0
}

\ ******************************************************************
\ *	music_init - start the tune (Layer 7)
\ ******************************************************************
\ *	Here rather than in bank 0 because vgm_init reads the .vgi header
\ *	out of music_lo below, which is in THIS bank: a starter in bank 0
\ *	could not page bank 3 in without paging itself out. Reached from
\ *	boot through bank3_call, which has already done the paging; all
\ *	this adds is HAZEL, where the player's code is, and that does not
\ *	page bank 3 out because it is a different window.
\ *
\ *	C = 1 is the player's "loop for ever", which is what the C64 does
\ *	with its own tune.
\ ******************************************************************

.music_init
{
    lda &fe34
    ora #HAZEL_BIT
    sta &fe34
IF MUSIC_AKL
    lda #LO(MUSIC_AKL_SONG)     ; the Arkos replay: song address, subsong 0
    ldx #HI(MUSIC_AKL_SONG)
    ldy #0
    jsr akl_init
ELSE
    lda #HI(HAZEL_WORK)
    ldx #LO(MUSIC_LO_BASE)
    ldy #HI(MUSIC_LO_BASE)
    sec
    jsr vgm_init
ENDIF
    lda &fe34
    and #255-HAZEL_BIT
    sta &fe34
    rts
}

\ ******************************************************************
\ *	The low half of the tune, ending exactly at &C000
\ ******************************************************************
\ *	The high half is the first thing in HAZEL, at &C000, so the two
\ *	are one contiguous block in the address map and the player reads
\ *	across the join without knowing it is there. That only works
\ *	because this bank and HAZEL are visible at the same time.
\ *
\ *	tools/export_music.py pads this half to exactly MUSIC_LO_SIZE, so
\ *	the join is at &C000 whatever the tune's length.
\ ******************************************************************

IF MUSIC_AKL

\ Nothing here in the Arkos build: the whole tune is tracker data and it
\ lives in HAZEL with the player, so all 8,960 bytes of this are free.
PRINT "BANK 3 code/data ends at", ~P%, "- no music_lo (MUSIC_AKL)"
PRINT "BANK 3 FREE ABOVE CODE =", ~&C000 - P%

ELSE

ASSERT P% <= MUSIC_LO_BASE
PRINT "BANK 3 code/data ends at", ~P%, "- music_lo starts at", ~MUSIC_LO_BASE

ORG MUSIC_LO_BASE
.music_lo
INCBIN "src/data/music_lo.bin"
ASSERT P% = HAZEL_BASE

ENDIF

.bank3_end

SAVE "BANK3", bank3_start, bank3_end

PRINT "------"
PRINT "BANK 3 - compiled sprite bodies"
PRINT "------"
PRINT "DATA size =",~bank3_end-bank3_start
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~&C000-P%
PRINT "------"
