\ ******************************************************************
\ *	bank1.asm
\ *	Sideways RAM bank 1 (slot SWRAM_SPRITES0): the sprite data for
\ *	pixel shift 0 - tables, then bounding-boxed MODE 2 frames.
\ *	Generated by tools/export_sprites.py; the layout is documented
\ *	there and mirrored by the constants at the top of src/sprite.asm.
\ ******************************************************************

CLEAR 0,&FFFF
ORG &8000
GUARD &C000
.bank1_start

.sprite_bank_0
IF GFX_CPC
INCBIN "src/data/sprites0-cpc.bin"
ELSE
INCBIN "src/data/sprites0.bin"
ENDIF

.bank1_end

SAVE "BANK1", bank1_start, bank1_end

PRINT "------"
PRINT "BANK 1 - sprites, shift 0"
PRINT "------"
PRINT "DATA size =",~bank1_end-bank1_start
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~&C000-P%
PRINT "------"
