\ ******************************************************************
\ *	bank2.asm
\ *	Sideways RAM bank 1 (slot SWRAM_SPRITES1): the sprite data for
\ *	pixel shift 1 - tables, then bounding-boxed MODE 2 frames.
\ *	Generated by tools/export_sprites.py; the layout is documented
\ *	there and mirrored by the constants at the top of src/sprite.asm.
\ ******************************************************************

CLEAR 0,&FFFF
ORG &8000
GUARD &C000
.bank2_start

.sprite_bank_1
IF GFX_CPC
INCBIN "src/data/sprites1-cpc.bin"
ELSE
INCBIN "src/data/sprites1.bin"
ENDIF

IF MUSIC_AKL = 0
\ The tune's B2 streams (decision 48). Nothing in this bank reads them:
\ they are here because the .vgi's eleven register streams do not have to be
\ in one place, and the tail of a sprite bank is a place. lib/vgiplayer.asm
\ pages this bank in for the byte and out again.
ASSERT P% <= MUSIC_B2_BASE
CLEAR MUSIC_B2_BASE, &C000
ORG MUSIC_B2_BASE
.music_b2
INCBIN "src/data/music_b2.bin"
.music_b2_end
ASSERT music_b2_end <= &C000
ENDIF

.bank2_end

SAVE "BANK2", bank2_start, bank2_end

PRINT "------"
PRINT "BANK 2 - sprites, shift 1"
PRINT "------"
PRINT "DATA size =",~bank2_end-bank2_start
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~&C000-P%
PRINT "------"
