\ ******************************************************************
\ *	music.asm - the HAZEL image: the VGI player and the tune
\ ******************************************************************
\ *	HAZEL is the Master's 8K of filing-system RAM at &C000-&DFFF,
\ *	paged in by ACCCON bit 3 (Y) over the MOS's VDU driver. It is the
\ *	only RAM left: main RAM below &2000 has tens of bytes and every
\ *	sideways bank is spoken for.
\ *
\ *	Three things make it the right home rather than a desperate one:
\ *
\ *	  - It does not overlap the sideways window, so the player is
\ *	    reachable from the IRQ no matter which bank the interrupted
\ *	    code had paged in - and the IRQ can fire inside the sprite
\ *	    engine, which pages 5, 6 and 7 as it goes.
\ *	  - The MOS's IRQ entry is at &E59E (read out of the vector at
\ *	    &FFFE on a Master, not recalled), which is ABOVE HAZEL, so
\ *	    paging HAZEL in cannot break interrupt dispatch. We only page
\ *	    it in inside our own handler anyway.
\ *	  - Its resident content is the filing system's workspace, and the
\ *	    filing system is finished with the moment the banks are loaded.
\ *	    MUSIC is therefore the LAST file loaded, of them all.
\ *
\ *	  &C000  the HIGH HALF of the tune. Its low half is at the top of
\ *	         sideways bank 3, ending exactly at &C000, and the two are
\ *	         one contiguous block: bank 3 and HAZEL are paged by
\ *	         different registers over different windows, so both are
\ *	         visible at once and the player reads across the join
\ *	         without knowing it is there.
\ *	  &D200  vgiplayer.asm: code and its resident decode state
\ *	  &D500  the player's ring workspace, 11 x 256, page aligned and
\ *	         reaching exactly to &DFFF. Not in the file: it is scratch,
\ *	         and vgm_init zeroes what it needs.
\ *
\ *	The player is lib/vgiplayer.asm from Repos/vgm-player-bbc, taken
\ *	unaltered. It decodes one byte per register stream per frame, so
\ *	its cost is flat rather than the VGC player's spiky RLE+LZ4 -
\ *	which is what a frame already at 90% needs. See docs/layer-7-music.md.
\ ******************************************************************

IF MUSIC_AKL

\ ******************************************************************
\ *	The Arkos build. Everything the music needs is in HAZEL:
\ *
\ *	  &C000  src/aklplayer.asm, the AKL tracker replay, and
\ *	         src/ay2sn.asm, the AY -> SN76489 conversion, with their
\ *	         tables and per-channel state
\ *	  &CC00  the WHOLE tune as Arkos tracker data, 4,741 bytes
\ *
\ *	No ring workspace, no half in bank 3, and no truncation: the
\ *	tune is 349 seconds instead of 203. What it costs is that the
\ *	SN76489 conversion happens at run time, per frame, instead of
\ *	offline with whole-song analysis - so it does not sound the same
\ *	as the VGI build. That is the comparison this switch exists for.
\ ******************************************************************

CLEAR 0, &FFFF
ORG HAZEL_BASE
GUARD MUSIC_AKL_SONG
.hazel_start

INCLUDE "src/aklplayer.asm"
INCLUDE "src/ay2sn.asm"
.akl_code_end

\ One frame of music: replay the tracker, then convert what it produced.
\ rupt_vsync calls this where the VGI build calls vgm_update.
.akl_frame
{
    jsr akl_play
    jmp ay2sn
}
.akl_frame_end

CLEAR MUSIC_AKL_SONG, MUSIC_AKL_SONG + 1
ORG MUSIC_AKL_SONG
GUARD &E000
.akl_song
INCBIN "src/data/music_akl.bin"
.akl_song_end
.hazel_end

HAZEL_LOAD_PAGES = (hazel_end - hazel_start + 255) DIV 256

SAVE "MUSIC", hazel_start, hazel_end

PRINT "------"
PRINT "HAZEL - the Arkos replay and the whole tune"
PRINT "------"
PRINT "PLAYER+CONVERTER size =", ~akl_frame_end - hazel_start
PRINT "PLAYER ROOM LEFT =", ~MUSIC_AKL_SONG - akl_frame_end
PRINT "TUNE size =", ~akl_song_end - akl_song
PRINT "LOAD PAGES =", HAZEL_LOAD_PAGES
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~&E000 - P%
PRINT "------"

ELSE

CLEAR 0, &FFFF
ORG HAZEL_BASE
GUARD MUSIC_PLAYER
.hazel_start

\ tools/export_music.py: the CPC port's EDGEA.SKS through SongToYm, ym2sn
\ and vgipacker. This is the upper part of region A - the rest of it is in
\ bank 3 below &C000, and a stream may lie across the join. The WHOLE
\ 349-second tune ships now; see decision 48 and the region table in
\ main.asm for where the other three regions are.
.music_hi
INCBIN "src/data/music_hi.bin"
.music_hi_end
ASSERT music_hi_end <= MUSIC_PLAYER

\ The guard was on the player's base so the tune could not run into it;
\ now put the player there. beebasm guards one address, so it has to be
\ cleared before anything is assembled at it.
CLEAR MUSIC_PLAYER, MUSIC_PLAYER+1
ORG MUSIC_PLAYER
GUARD HAZEL_WORK

\ The map FIRST, because it is what the player is built around under
\ VGI_SPLIT: eleven addresses, eleven ROMSEL bytes and the frame count,
\ generated by tools/export_music.py and ASSERTing main.asm's region
\ constants against the ones it placed the streams with.
INCLUDE "src/data/music_map.asm"
.vgi_map_end

INCLUDE "lib/vgiplayer.asm"

.hazel_end
ASSERT VGI_STATE + VGI_STATE_SIZE <= &0D00

HAZEL_LOAD_PAGES = (hazel_end - hazel_start + 255) DIV 256

SAVE "MUSIC", hazel_start, hazel_end

PRINT "------"
PRINT "HAZEL - the VGI player and the tune"
PRINT "------"
PRINT "PLAYER size =", ~hazel_end - vgm_start
PRINT "STREAM MAP size =", ~vgi_map_end - MUSIC_PLAYER
PRINT "PLAYER ROOM LEFT =", ~HAZEL_WORK - hazel_end
PRINT "REGION A size =", ~MUSIC_A_TOP - MUSIC_A_BASE
PRINT "REGION A ROOM LEFT =", ~MUSIC_PLAYER - music_hi_end
PRINT "VGI STATE at", ~VGI_STATE, "size", ~VGI_STATE_SIZE
PRINT "LOAD PAGES =", HAZEL_LOAD_PAGES
PRINT "HIGH WATERMARK =", ~P%
PRINT "FREE =", ~HAZEL_WORK - P%
PRINT "------"

ENDIF ; MUSIC_AKL
