\ ******************************************************************
\ *	sprite.asm
\ *	The sprite engine (Layer 3): eight software sprites over the
\ *	scrolling play buffer, in both shadow banks.
\ *
\ *	This is the port of the C64's xploder_1 / xploder_2 (rout1): the
\ *	game keeps sprite_pos, sprite_dp and sprite_pls_tmr exactly as the
\ *	original does, and once a frame the engine turns them into pixels.
\ *	Slot 0 is the player, 1 the bullet, 2-7 the enemy pool - the C64's
\ *	arrangement (sprite_pos+$00 player, +$02 bullet, +$04 up enemies).
\ *
\ *	Lifted from Paradroid's sprite.asm (its docs/layer-5-blitter.md)
\ *	and cut to what a Master 128 with a 16K wrapped buffer needs:
\ *
\ *	- MASKS ARE NOT STORED. A transparent pixel is logical 0, so a
\ *	  256-byte table recovers the AND mask from the data byte. Sprites
\ *	  may not use logical 0; black inside a sprite is logical 8, which
\ *	  setup_display's palette maps back to physical black.
\ *	- THE SAVE AREA MIRRORS SCREEN GEOMETRY. Within a character row a
\ *	  byte is at col*8 + scan, so one Y addresses both (bufp),Y and
\ *	  (svp),Y and nothing needs X. One 256-byte page per slot per bank
\ *	  at SPR_SAVE: 21 scanlines from any alignment touch at most four
\ *	  character rows, and 3*56 + 6*8 + 7 = 223 < 256, so svp never
\ *	  carries out of its page.
\ *	- THE RESTORE REPLAYS THE DRAW'S WALK from the start pointer,
\ *	  scanline, row count and column count the draw stored. Nothing
\ *	  else is remembered, and the two therefore cannot disagree.
\ *	- RESTORE ALL, THEN SCROLL, THEN DRAW ALL. Restore runs slot 0 up,
\ *	  draw runs slot 7 down, so the player is drawn last and on top,
\ *	  which is the C64's sprite priority. A draw between another
\ *	  sprite's restore and its draw would capture that sprite into the
\ *	  save; the new scroll column between them is harmless.
\ *	- CLIPPED, NOT CULLED (decision 2). The draw clips the frame's
\ *	  bounding box to 80 columns x 160 scanlines and saves and draws
\ *	  only what is left. A buffer row is exactly the display width, so
\ *	  an unclipped column off one edge would land on the other.
\ *	- EVERYTHING IS INTERPRETED. The data is bounding-boxed and
\ *	  row-major with the frame's box width as its stride
\ *	  (tools/export_sprites.py). Each pixel shift has its own 16K bank,
\ *	  so a sprite pages in the bank its shift wants and reads one byte
\ *	  per column: (src),Y with Y = column, then (bufp),Y with Y =
\ *	  column*8. About 37 cycles a byte and 40 a row.
\ *	- HIT FLASH IS THE ORA TABLE. `ora LUT,x` reaches the identity
\ *	  table normally and a recolouring one while sprite_pls_tmr runs.
\ *	  The C64 swaps the sprite's colour register; our colours are baked
\ *	  into the pixels, so the table recolours them on the way through
\ *	  at no cost per byte. Seven patch sites, written only when the
\ *	  table changes.
\ ******************************************************************

\ ---- geometry -----------------------------------------------------
\ Screen fat pixel x of a sprite = C64 sprite_pos x - SPR_X_OFF (the
\ C64 stores x halved: hardware x = 2x, and hardware x 24 is bitmap
\ pixel 0, so 24/2 = 12). Scanline y = C64 y - SPR_Y_OFF: the C64
\ bitmap starts at raster 50 and our play area starts PANEL_ROWS
\ character rows down. Both to be confirmed against the original when
\ the player moves for real (Layer 4).
SPR_X_OFF = 12
SPR_Y_OFF = 50 + PANEL_ROWS * 8

SPR_SLOTS = 8
\ sprite_dp_dcd entry $0a, the explosion's last frame, which is empty:
\ the C64's way of hiding a sprite without a flag of its own.
SPR_DP_BLANK = &0a
SPR_W     = 7               ; 24 px = 6 bytes, plus the shift's spill byte
SPR_H     = 21
SPR_BLOCK = SPR_W * 8       ; 56: one character row of save area
PLAY_COLS = 80
PLAY_LINES = PLAY_ROWS * 8  ; 160

\ 21 scanlines from any alignment cross at most three character rows,
\ so the furthest byte a row can reach past bufp is this. The whole
\ sprite clears the 16K wrap if bufp plus this does.
SPR_REACH = 3 * row_stride + (SPR_W - 1) * 8

ASSERT 3 * SPR_BLOCK + (SPR_W - 1) * 8 + 7 < 256
ASSERT (SPR_SAVE AND &FF) = 0
ASSERT SPR_SAVE + 2 * SPR_SLOTS * 256 <= PANEL_ADDR

\ ---- the sprite banks ---------------------------------------------
\ src/data/sprites0.bin and sprites1.bin, one per pixel shift, the same
\ layout in each. Generated by tools/export_sprites.py, which is where
\ this map is documented.
SPR_MASK      = &8000       ; data byte -> AND mask
SPR_LUT_IDENT = &8100       ; data byte -> itself
spr_frame_lo  = &8400       ; frame -> its box data in this bank
spr_frame_hi  = &8480
spr_box_r0    = &8500       ; first opaque row, at this shift
spr_box_rn    = &8580       ; rows; 0 = a blank frame
spr_box_c0    = &8600       ; first opaque byte column
spr_box_cn    = &8680       ; byte columns = the data's row stride
spr_dp_dcd    = &8700       ; the C64's sprite_dp_dcd, rebased to frame 0-118
spr_lut_dcd   = &8780       ; page of the LUT this dp's flash uses
spr_comp_lo   = &8800       ; frame -> its descriptor in SWRAM_COMPILED, 0 = none
spr_comp_hi   = &8880

\ The four bytes of a descriptor, in slot 7 (decision 29).
SPR_COMP_DLO = 0
SPR_COMP_DHI = 1
SPR_COMP_RLO = 2
SPR_COMP_RHI = 3

\ spr_wrap, and spr_sv_wrap, which is what tells the restore what to replay.
SPR_MODE_PLAIN = 0
SPR_MODE_SPLIT = 1
SPR_MODE_COMP  = 2

\ ******************************************************************
\ *	SCANSTEP - bufp and svp one scanline on
\ ******************************************************************
\ +1 inside a character row; the crossing, one step in eight, is out of
\ line. THE SCANLINE IS IN bufp: every term of it is a multiple of 8
\ except the scanline itself, so `bufp AND 7` is the scanline and no
\ counter is needed. THE PAGE CARRY IS DEFERRED into the crossing tail
\ (Paradroid, hexwab): a low byte that has just wrapped to 0 has
\ `bufp AND 7` = 0 too, so that step always takes the branch and the
\ carry can be handled once there instead of tested every step.
\ P%+5 skips the JSR - a macro body cannot declare a label, because the
\ second expansion would redefine it.

MACRO SCANSTEP
    inc svp
    inc bufp
    lda bufp
    and #7
    bne P%+5
    jsr spr_scan_row
ENDMACRO

\ The crossing tail. bufp is already on what would be scanline 8, so
\ both pointers move on by stride - 8. It also finishes the INC the
\ macro left half done, and the 16K wrap is inline: past &7FFF is bit 7
\ set, and the correction is one high-byte SBC with carry known clear.
.spr_scan_row
{
    clc
    lda svp
    adc #SPR_BLOCK-8
    sta svp
    clc
    lda bufp
    bne P%+4
    inc bufp+1
    adc #LO(row_stride-8)
    sta bufp
    lda bufp+1
    adc #HI(row_stride-8)
    bpl nowrap
    sbc #HI(screen_size)-1      ; carry is clear here
    .nowrap
    sta bufp+1

    \ A new character row, which is the only place a sprite's split
    \ column can change - see spr_split_calc. Five cycles for the
    \ sprites that do not straddle, which is nearly all of them.
    lda spr_wrap
    beq out
    jsr spr_split_calc
    .out
    rts
}

\ ******************************************************************
\ *	spr_split_calc - where this character row leaves the buffer
\ ******************************************************************
\ spr_split = how many of the row's byte columns lie before the end of
\ the 16K buffer, or 0 if all of them do.
\ THE ANSWER IS THE SAME FOR ALL EIGHT SCANLINES OF A CHARACTER ROW.
\ Every term of a byte's address except the scanline is a multiple of 8
\ - the buffer origin, the row offset, the column - so the columns sit
\ at base + scan + 0, 8, 16 ... and which of them fit before &8000
\ does not depend on scan. bufp AND 7 IS the scanline, so the base is
\ bufp minus it, and the distance to the end is &8000 - base. Divided
\ by 8 that is the count, and 256 bytes or more of it means nowhere
\ near the end.

.spr_split_calc
{
    lda bufp
    and #7                      ; the scanline
    sec
    sbc bufp
    tay                         ; LO(&8000 - base)
    lda #HI(screen_top)
    sbc bufp+1
    bne whole                   ; 256 bytes or more still to go
    tya
    lsr a : lsr a : lsr a       ; byte columns that fit
    cmp spr_count
    bcc out                     ; 1 to count-1: the row is split here
    .whole
    lda #0
    .out
    sta spr_split
    rts
}

\ ******************************************************************
\ *	spr_restore_all - put every slot's background back
\ ******************************************************************
\ In the bank the CPU is writing, which is the hidden one. Slot 0 up,
\ so that where two sprites overlap the background comes back in the
\ reverse of the order it was covered. Main RAM and the buffer only:
\ no bank paging, the restore never looks at a pixel.

.spr_restore_all
{
    jsr spr_set_bank8
    ldx #0
    .loop
    stx spr_slot
    txa
    ora spr_bank8
    tay
    lda spr_sv_on, y
    beq next
    jsr spr_restore_slot
    ldx spr_slot
    .next
    inx
    cpx #SPR_SLOTS
    bne loop

    \ A compiled slot pages SWRAM_COMPILED in; everything outside this
    \ file assumes SWRAM_DATA, and the scroll reads char_data next.
    lda #SWRAM_DATA
    sta &f4
    sta &fe30
    rts
}

\ Y = spr_bank8 + slot. Replays the walk the draw took.
.spr_restore_slot
{
    lda spr_sv_lo, y
    sta bufp
    lda spr_sv_hi, y
    sta bufp+1
    lda spr_sv_scan, y
    sta svp
    tya
    clc
    adc #HI(SPR_SAVE)
    sta svp+1
    lda spr_sv_rows, y
    sta spr_rows
    lda spr_sv_cols, y
    sta spr_count
    tax
    lda spr_rest_entry_lo-1, x
    sta spr_entry               ; the whole-row body, for spr_rest_row_split
    lda spr_rest_entry_hi-1, x
    sta spr_entry+1
    lda spr_sv_wrap, y
    sta spr_wrap                ; spr_scan_row watches this
    cmp #SPR_MODE_COMP
    beq compiled
    lda spr_wrap
    bne wrapped
    lda spr_entry
    sta call+1
    lda spr_entry+1
    sta call+2
    bne rows                    ; always: the entries are not in page 0
    .compiled                   ; the only bank the restore ever pages in;
    lda #SWRAM_COMPILED         ; spr_restore_all puts SWRAM_DATA back
    sta &f4
    sta &fe30
    lda spr_sv_clo, y
    sta ccall+1
    lda spr_sv_chi, y
    sta ccall+2
    .ccall
    jsr &ffff                   ; it walks every row itself
    rts

    .wrapped
    jsr spr_split_calc          ; the first character row
    lda #LO(spr_rest_row_split)
    sta call+1
    lda #HI(spr_rest_row_split)
    sta call+2

    .rows
    .call
    jsr &ffff                   ; patched: the body for this column count
    dec spr_rows
    beq done
    SCANSTEP
    jmp rows
    .done
    rts
}

\ Restore bodies, entered at (column count), each falling through to
\ the next. Seven columns are 8 bytes apart in address order, which is
\ what lets one Y address the screen and the save alike.
.spr_rest_row7
    ldy #6*8 : lda (svp), y : sta (bufp), y
.spr_rest_row6
    ldy #5*8 : lda (svp), y : sta (bufp), y
.spr_rest_row5
    ldy #4*8 : lda (svp), y : sta (bufp), y
.spr_rest_row4
    ldy #3*8 : lda (svp), y : sta (bufp), y
.spr_rest_row3
    ldy #2*8 : lda (svp), y : sta (bufp), y
.spr_rest_row2
    ldy #1*8 : lda (svp), y : sta (bufp), y
.spr_rest_row1
    ldy #0   : lda (svp), y : sta (bufp), y
    rts

.spr_rest_entry_lo
    EQUB LO(spr_rest_row1), LO(spr_rest_row2), LO(spr_rest_row3), LO(spr_rest_row4)
    EQUB LO(spr_rest_row5), LO(spr_rest_row6), LO(spr_rest_row7)
.spr_rest_entry_hi
    EQUB HI(spr_rest_row1), HI(spr_rest_row2), HI(spr_rest_row3), HI(spr_rest_row4)
    EQUB HI(spr_rest_row5), HI(spr_rest_row6), HI(spr_rest_row7)

\ The bodies for a character row that crosses the end of the buffer:
\ two ordinary ladder calls instead of one. See spr_draw_row_split for
\ the whole story - this is the same thing without the data pointer.

.spr_rest_row_split
{
    lda spr_split
    bne split
    jmp (spr_entry)             ; this character row is whole

    .split
    tax                         ; columns 0 to k-1
    lda spr_rest_entry_lo-1, x
    sta c1+1
    lda spr_rest_entry_hi-1, x
    sta c1+2
    lda spr_count               ; and k to count-1
    sec
    sbc spr_split
    tax
    lda spr_rest_entry_lo-1, x
    sta c2+1
    lda spr_rest_entry_hi-1, x
    sta c2+2

    .c1
    jsr &ffff

    lda spr_split
    asl a : asl a : asl a
    sta spr_bias                ; k*8, the same along both pointers
    clc
    lda svp : adc spr_bias : sta svp
    clc
    lda bufp : adc spr_bias : sta bufp
    lda bufp+1 : adc #0
    sec
    sbc #HI(screen_size)        ; and back round the 16K buffer
    sta bufp+1

    .c2
    jsr &ffff

    sec                         ; put them back: the caller's SCANSTEP
    lda svp : sbc spr_bias : sta svp        ; walks the unbiased pointers
    sec
    lda bufp : sbc spr_bias : sta bufp
    lda bufp+1 : sbc #0
    clc
    adc #HI(screen_size)
    sta bufp+1
    rts
}

\ ******************************************************************
\ *	spr_draw_all - save the background under every slot and draw it
\ ******************************************************************
\ Slot 7 down, so the player (slot 0) is drawn last and on top. Pages
\ the sprite bank in per slot, because which of the two a sprite wants
\ is a property of its x, and leaves SWRAM_DATA in - the resting state
\ everything outside this file assumes.

.spr_draw_all
{
    jsr spr_set_bank8
    ldx #SPR_SLOTS-1
    .loop
    stx spr_slot
    jsr spr_draw_slot
    ldx spr_slot
    dex
    bpl loop
    lda #SWRAM_DATA
    sta &f4
    sta &fe30
    rts
}

\ ******************************************************************
\ *	spr_straddle_exact - does a row of this sprite really cross &8000?
\ ******************************************************************
\ Called only when the cheap SPR_REACH test says it might, which is 12%
\ of sprites; about one in ten of those really does. Sets spr_wrap.
\
\ SPR_REACH is how far the walk reaches VERTICALLY - three character
\ rows and change - but a row only straddles if its own columns do, a
\ reach of at most 55 bytes. So ask spr_split_calc's question of each
\ character row the sprite touches instead: at most four of them, and
\ the answer within one is the same for all eight of its scanlines.

.spr_straddle_exact
{
    sec                         ; the first character row's base
    lda bufp
    sbc spr_scan
    sta spr_tmp
    lda bufp+1
    sbc #0
    sta spr_tmp+1

    lda spr_scan                ; character rows touched, 1 to 4
    clc
    adc spr_rows
    adc #7
    lsr a : lsr a : lsr a
    tax

    .seg_loop
    sec                         ; bytes from this base to the end
    lda #0
    sbc spr_tmp
    tay
    lda #HI(screen_top)
    sbc spr_tmp+1
    bne next_seg                ; 256 or more: nowhere near it
    tya
    lsr a : lsr a : lsr a       ; byte columns that fit before the end
    cmp spr_count
    bcs next_seg                ; all of them: this row is whole
    inc spr_wrap                ; 1 to count-1: this row is split
    rts

    .next_seg
    dex
    beq done
    clc                         ; on to the next character row
    lda spr_tmp
    adc #LO(row_stride)
    sta spr_tmp
    lda spr_tmp+1
    adc #HI(row_stride)
    bpl no_wrap
    sbc #HI(screen_size)-1      ; carry is clear here
    .no_wrap
    sta spr_tmp+1
    jmp seg_loop

    .done
    rts
}

\ spr_bank8 = 8 for the shadow bank, 0 for main: the per-slot state is
\ kept per bank, because a bank is redrawn every other game frame and
\ the background under a sprite is whatever THAT bank held.
.spr_set_bank8
{
    lda &fe34
    and #4                      ; X bit: the bank the CPU writes
    asl a
    sta spr_bank8
    rts
}

\ X = slot. Clips the frame's bounding box to the play area, works out
\ the pointers, records what the restore will need, and draws.
.spr_draw_slot
{
    txa
    ora spr_bank8
    sta spr_idx
    tay
    lda #0
    sta spr_sv_on, y            ; nothing to put back unless the draw happens

    \\ ---- position -------------------------------------------------
    \\ x is in fat pixels, and the bank's own picture is one pixel
    \\ further along than the other's, so a sprite that is to stand
    \\ still on screen moves with it: bank phase is added to x before
    \\ the byte column and the pixel shift are split out of it. The
    \\ shift picks the bank; the column is the arithmetic half, so the
    \\ CMP/ROR pair rather than an LSR.
    txa
    asl a
    tay
    lda sprite_pos+1, y
    sta spr_y

    \\ v = x - SPR_X_OFF + phase runs -12 to 244, which DOES NOT FIT A
    \\ SIGNED BYTE. This used to halve it with CMP #&80 : ROR, an
    \\ arithmetic shift that reads bit 7 as the sign - so every sprite at
    \\ x >= 140 came out with a large negative column, was taken to be off
    \\ the left edge and was never drawn. Enemies spawning at x = 172, the
    \\ far right edge, stayed invisible until they had crossed a third of
    \\ the screen (BUGS.md #8). The sign has to come from the subtraction's
    \\ carry instead, so the phase is folded into the constant to keep that
    \\ carry meaningful, and the halving is logical when v >= 0.
    lda #SPR_X_OFF
    sec
    sbc spr_phase
    sta spr_c
    lda sprite_pos, y
    sec
    sbc spr_c                   ; carry set = v >= 0
    sta spr_c
    php                         ; the bank select below clears carry
    and #1
    clc
    adc #SWRAM_SPRITES0
    sta &f4
    sta &fe30
    lda spr_c
    plp
    bcs x_positive
    sec                         ; v < 0: arithmetic, keep the sign
    ror a
    jmp x_done
    .x_positive
    lsr a                       ; v >= 0: logical, 0-244 becomes 0-122
    .x_done
    sta spr_c                   ; signed byte column of the left edge.
                                ; enemy_bounds keeps x under &d0, so the
                                ; column stays under 98 and C below cannot
                                ; reach &80 and be mistaken for negative.

    \\ ---- the frame and its box ------------------------------------
    ldx spr_slot
    ldy sprite_dp, x
    lda spr_dp_dcd, y
    sta spr_frame
    tay
    lda spr_box_rn, y
    bne P%+5                    ; a blank frame: nothing to draw. The exits
    jmp off                     ; below are all out of branch range of .off
    sta spr_rows
    lda spr_box_cn, y
    sta spr_cols
    sta stride+1                ; the data's row stride

    \\ ---- columns --------------------------------------------------
    \\ The box's leftmost column C is signed, -6 to 127. Drawn columns
    \\ are max(C,0) to min(C + cn - 1, 79); the ones clipped off the
    \\ left are skipped in the data pointer instead.
    lda spr_box_c0, y
    clc
    adc spr_c
    sta spr_c
    bmi left_clip
    cmp #PLAY_COLS
    bcc P%+5                    ; wholly off the right
    jmp off
    sta spr_c0
    lda #0
    beq cols_right              ; always
    .left_clip
    eor #&ff
    clc
    adc #1                      ; -C: columns to skip in the data
    ldx #0
    stx spr_c0
    .cols_right
    sta spr_skip_c
    lda spr_c
    clc
    adc spr_cols
    sec
    sbc #1                      ; C + cn - 1, the box's last column
    bpl P%+5                    ; wholly off the left
    jmp off
    cmp #PLAY_COLS
    bcc last_ok
    lda #PLAY_COLS-1
    .last_ok
    sec
    sbc spr_c0
    clc
    adc #1
    sta spr_count               ; columns actually drawn, 1 to 7

    \\ ---- rows -----------------------------------------------------
    \\ The box's first row R = y - SPR_Y_OFF + box_r0 runs -90 to 185,
    \\ so it is done in two halves on the carry out of the subtraction.
    lda spr_y
    sec
    sbc #SPR_Y_OFF
    bcc above
    clc
    adc spr_box_r0, y           ; R, 0 to 185
    cmp #PLAY_LINES
    bcc P%+5                    ; wholly off the bottom
    jmp off
    sta spr_r0
    lda #0
    sta spr_skip_r
    lda spr_r0
    clc
    adc spr_rows
    cmp #PLAY_LINES+1
    bcc rows_ok
    lda #PLAY_LINES             ; clipped at the bottom
    sec
    sbc spr_r0
    sta spr_rows
    jmp rows_ok
    .above                      ; A holds R - box_r0 in two's complement
    clc
    adc spr_box_r0, y           ; carry set iff R >= 0
    bcs top_visible
    eor #&ff
    clc
    adc #1                      ; -R: rows clipped off the top
    sta spr_skip_r
    lda spr_rows
    sec
    sbc spr_skip_r
    bne P%+5                    ; wholly off the top
    jmp off
    bpl P%+5
    jmp off
    sta spr_rows
    lda #0
    sta spr_r0
    beq rows_ok                 ; always
    .top_visible                ; R is 0 to 19: nothing clipped
    sta spr_r0
    lda #0
    sta spr_skip_r
    .rows_ok

    \\ ---- bufp = the sprite's top left byte ------------------------
    \\ The origin of the picture this frame is corner_addr + 8: the
    \\ scroll writes the new column at corner_addr + 640 and the view
    \\ moves on by one column at the end of the frame, so what is
    \\ displayed is the window that ends on that new column. Then
    \\ + row DIV 8 * 640 + column * 8 + row MOD 8, wrapped at 16K.
    lda spr_r0
    and #7
    sta spr_scan
    \\ + character row * 640. The two 32-entry tables this used are gone,
    \\ to make room: 640 is &280, so LO(n*640) is 0 or 128 by the parity
    \\ of n, and HI(n*640) is (5n) >> 1 - one shift that hands the parity
    \\ over in the carry on its way past.
    lda spr_r0
    lsr a : lsr a : lsr a       ; n, the character row 0-19
    sta spr_tmp
    asl a : asl a               ; 4n
    clc
    adc spr_tmp                 ; 5n
    lsr a                       ; HI(n*640), carry = n AND 1
    sta spr_tmp
    lda #0
    bcc row_even
    lda #128                    ; LO(n*640)
    .row_even
    clc
    adc corner_addr
    sta bufp
    lda corner_addr+1
    adc spr_tmp
    sta bufp+1
    \\ + column * 8, its 80-entry tables gone the same way. spr_c0 is
    \\ 0-79, so c*8 is under 640: the high byte is c >> 5 and the low is
    \\ (c AND 31) * 8. The high half first, because the shifts would eat
    \\ the low half's carry.
    lda spr_c0
    lsr a : lsr a : lsr a : lsr a : lsr a
    sta spr_tmp
    lda spr_c0
    and #31
    asl a : asl a : asl a
    clc
    adc bufp
    sta bufp
    lda bufp+1
    adc spr_tmp
    sta bufp+1
    lda spr_scan
    clc
    adc #8                      ; the origin, see above
    adc bufp
    sta bufp
    bcc no_carry
    inc bufp+1
    .no_carry
    lda bufp+1
    bpl no_wrap
    sec
    sbc #HI(screen_size)
    sta bufp+1
    .no_wrap

    \\ Can any of this sprite's rows straddle the end of the buffer?
    \\ SPR_REACH is the furthest byte the walk can touch beyond bufp, so
    \\ clear of that and every row takes the fast path blind - true about
    \\ 88% of the time, and 12 cycles to establish. But it is a very
    \\ loose test: the walk only reaches that far VERTICALLY, and a row
    \\ straddles only if its own seven columns do. Of the 12% it flags,
    \\ about one in ten really straddles, and the other nine were paying
    \\ 97 cycles a byte for nothing. So the flagged ones ask properly.
    lda #0
    sta spr_wrap
    clc
    lda bufp
    adc #LO(SPR_REACH)
    lda bufp+1
    adc #HI(SPR_REACH)
    bpl no_straddle
    jsr spr_straddle_exact
    .no_straddle

    \\ ---- svp = this slot's save page in this bank -----------------
    lda spr_scan
    sta svp
    lda spr_idx
    clc
    adc #HI(SPR_SAVE)
    sta svp+1

    \\ ---- src = the frame's data, past everything clipped ----------
    ldy spr_frame
    lda spr_frame_lo, y
    clc
    adc spr_skip_c
    sta src
    lda spr_frame_hi, y
    adc #0
    sta src+1
    ldx spr_skip_r
    beq no_skip
    .skip_loop
    lda src
    clc
    adc spr_cols
    sta src
    bcc skip_next
    inc src+1
    .skip_next
    dex
    bne skip_loop
    .no_skip

    \\ ---- what the restore will replay -----------------------------
    ldy spr_idx
    lda bufp
    sta spr_sv_lo, y
    lda bufp+1
    sta spr_sv_hi, y
    lda spr_scan
    sta spr_sv_scan, y
    lda spr_rows
    sta spr_sv_rows, y
    lda spr_count
    sta spr_sv_cols, y
    lda spr_wrap
    sta spr_sv_wrap, y
    lda #1
    sta spr_sv_on, y

    \\ ---- a compiled body, if this frame has one and nothing has been
    \\ clipped off it. Its pixels are immediates, so it reads no sprite
    \\ data and lives in a bank of its own; it walks every row itself
    \\ and returns, so the row loop below is skipped whole (decision 29).
    ldy spr_frame
    lda spr_comp_hi, y
    beq not_compiled            ; no compiled body for this frame
    sta spr_entry+1
    lda spr_comp_lo, y
    sta spr_entry

    lda spr_skip_c              ; clipped off the left or the top?
    ora spr_skip_r
    ora spr_wrap                ; or a row over the end of the buffer?
    bne not_compiled
    lda spr_box_cn, y           ; clipped off the right or the bottom?
    cmp spr_count
    bne not_compiled
    lda spr_box_rn, y
    cmp spr_rows
    bne not_compiled

    lda #SWRAM_COMPILED
    sta &f4
    sta &fe30
    ldy #SPR_COMP_DLO
    lda (spr_entry), y
    sta comp_call+1
    ldy #SPR_COMP_DHI
    lda (spr_entry), y
    sta comp_call+2
    ldx spr_idx                 ; what the restore will need
    ldy #SPR_COMP_RLO
    lda (spr_entry), y
    sta spr_sv_clo, x
    ldy #SPR_COMP_RHI
    lda (spr_entry), y
    sta spr_sv_chi, x
    lda #SPR_MODE_COMP
    sta spr_sv_wrap, x
    .comp_call
    jsr &ffff
    rts

    .not_compiled
    \\ ---- the row body ---------------------------------------------
    ldx spr_count
    lda spr_draw_entry_lo-1, x
    sta spr_entry               ; the whole-row body, for spr_draw_row_split
    lda spr_draw_entry_hi-1, x
    sta spr_entry+1
    lda spr_wrap
    bne wrapped
    lda spr_entry
    sta call+1
    lda spr_entry+1
    sta call+2
    bne lut                     ; always
    .wrapped
    jsr spr_split_calc          ; the first character row
    lda #LO(spr_draw_row_split)
    sta call+1
    lda #HI(spr_draw_row_split)
    sta call+2

    \\ ---- the ORA table: identity, or this frame's hit flash --------
    .lut
    ldx spr_slot
    lda sprite_pls_tmr, x
    beq no_flash
    ldy sprite_dp, x
    lda spr_lut_dcd, y
    bne set_lut                 ; always: it is a page in &81-&83
    .no_flash
    lda #HI(SPR_LUT_IDENT)
    .set_lut
    cmp spr_lut_cur
    beq lut_ok
    sta spr_lut_cur
    sta spr_lut6+2
    sta spr_lut5+2
    sta spr_lut4+2
    sta spr_lut3+2
    sta spr_lut2+2
    sta spr_lut1+2
    sta spr_lut0+2
    .lut_ok

    .rows
    .call
    jsr &ffff                   ; patched: the body for this column count
    dec spr_rows
    beq off
    lda src
    clc
    .stride
    adc #SPR_W                  ; patched: the frame's box width
    sta src
    bcc same_page
    inc src+1
    .same_page
    SCANSTEP
    jmp rows

    .off
    rts
}

\ Draw bodies, entered at (column count) and falling through to the
\ next. Per column: the data byte into X, the background saved, masked,
\ the sprite ORed in through the colour table, stored back.
MACRO SPR_DRAW_COL n
    ldy #n
    lda (src), y
    tax
    ldy #n*8
    lda (bufp), y
    sta (svp), y
    and SPR_MASK, x
ENDMACRO

.spr_draw_row7
    SPR_DRAW_COL 6
    .spr_lut6 ora SPR_LUT_IDENT, x
    sta (bufp), y
.spr_draw_row6
    SPR_DRAW_COL 5
    .spr_lut5 ora SPR_LUT_IDENT, x
    sta (bufp), y
.spr_draw_row5
    SPR_DRAW_COL 4
    .spr_lut4 ora SPR_LUT_IDENT, x
    sta (bufp), y
.spr_draw_row4
    SPR_DRAW_COL 3
    .spr_lut3 ora SPR_LUT_IDENT, x
    sta (bufp), y
.spr_draw_row3
    SPR_DRAW_COL 2
    .spr_lut2 ora SPR_LUT_IDENT, x
    sta (bufp), y
.spr_draw_row2
    SPR_DRAW_COL 1
    .spr_lut1 ora SPR_LUT_IDENT, x
    sta (bufp), y
.spr_draw_row1
    SPR_DRAW_COL 0
    .spr_lut0 ora SPR_LUT_IDENT, x
    sta (bufp), y
    rts

.spr_draw_entry_lo
    EQUB LO(spr_draw_row1), LO(spr_draw_row2), LO(spr_draw_row3), LO(spr_draw_row4)
    EQUB LO(spr_draw_row5), LO(spr_draw_row6), LO(spr_draw_row7)
.spr_draw_entry_hi
    EQUB HI(spr_draw_row1), HI(spr_draw_row2), HI(spr_draw_row3), HI(spr_draw_row4)
    EQUB HI(spr_draw_row5), HI(spr_draw_row6), HI(spr_draw_row7)

\ ******************************************************************
\ *	spr_draw_row_split - the character row that leaves the buffer
\ ******************************************************************
\ Replaces the walked fallback that served this case at 97 cycles a byte
\ against 36, and cost it on nine sprites in ten that never needed it
\ (BUGS.md #9).
\
\ AT MOST ONE CHARACTER ROW OF A SPRITE CAN STRADDLE: consecutive ones
\ are 640 bytes apart and a sprite is at most 56 wide. That row's eight
\ scanlines are drawn as two ordinary ladder calls - columns 0 to k-1
\ where the pointers already are, then k to count-1 the same distance
\ along the save and the data but 16K back round the buffer. BOTH
\ POINTERS TAKE THE SAME BIAS, k*8, which is the whole trick: the
\ existing unrolled bodies serve the second half unchanged and there is
\ no second ladder. Every other character row takes the whole-row body,
\ reached by a tail JMP so its own RTS returns to the row loop.

.spr_draw_row_split
{
    lda spr_split
    bne split
    jmp (spr_entry)             ; this character row is whole

    .split
    tax                         ; columns 0 to k-1
    lda spr_draw_entry_lo-1, x
    sta c1+1
    lda spr_draw_entry_hi-1, x
    sta c1+2
    lda spr_count               ; and k to count-1
    sec
    sbc spr_split
    tax
    lda spr_draw_entry_lo-1, x
    sta c2+1
    lda spr_draw_entry_hi-1, x
    sta c2+2

    .c1
    jsr &ffff

    lda spr_split
    asl a : asl a : asl a
    sta spr_bias                ; k*8, the same along screen and save
    clc
    lda svp : adc spr_bias : sta svp
    clc
    lda bufp : adc spr_bias : sta bufp
    lda bufp+1 : adc #0
    sec
    sbc #HI(screen_size)        ; and back round the 16K buffer
    sta bufp+1
    clc
    lda src : adc spr_split : sta src   ; the data is k bytes along
    bcc c2
    inc src+1

    .c2
    jsr &ffff

    sec                         ; put them back: the caller's SCANSTEP
    lda svp : sbc spr_bias : sta svp        ; walks the unbiased pointers
    sec
    lda bufp : sbc spr_bias : sta bufp
    lda bufp+1 : sbc #0
    clc
    adc #HI(screen_size)
    sta bufp+1
    sec
    lda src : sbc spr_split : sta src
    bcs out
    dec src+1
    .out
    rts
}

.spr_lut_cur EQUB HI(SPR_LUT_IDENT)

\ ******************************************************************
\ *	spr_init - every sprite hidden, nothing saved in either bank
\ ******************************************************************
\ The C64's own cm_hide_sprs: zero sprite_pos and point every sprite at
\ a frame with nothing in it.

.spr_init
{
    ldx #2*SPR_SLOTS-1
    lda #0
    .clear_pos
    sta sprite_pos, x
    dex
    bpl clear_pos

    ldx #2*SPR_SLOTS-1
    lda #0
    .clear_saves
    sta spr_sv_on, x
    dex
    bpl clear_saves

    ldx #SPR_SLOTS-1
    .clear_slots
    lda #0
    sta sprite_pls_tmr, x
    lda #SPR_DP_BLANK
    sta sprite_dp, x
    dex
    bpl clear_slots

    lda #0
    sta spr_phase
    rts
}
