\ Generated by tools/compile_sprites.py - do not edit.
\ The compiled sprite bodies have these baked into them; if the zero
\ page moves under them they must be regenerated, so fail the build.
ASSERT bufp = &0E
ASSERT svp = &10
ASSERT row_stride = 640
ASSERT screen_size = &4000
ASSERT SPR_BLOCK = 56
COMPILED_FRAMES = 2
