\ GENERATED by tools/export_music.py - do not edit.
\
\ Where each of the .vgi's eleven register streams was placed, and
\ which ROMSEL byte makes it readable. vgm_stream_mount copies these
\ into the player's per-stream pointers, and fetchbyte writes the
\ ROMSEL byte to &FE30 before every read. See decision 48.

ASSERT MUSIC_A_BASE    = &9100
ASSERT MUSIC_A_JOIN    = &C000
ASSERT MUSIC_A_TOP     = &D300
ASSERT MUSIC_ANDY_BASE = &8000
ASSERT MUSIC_ANDY_TOP  = &9000
ASSERT MUSIC_B1_BASE   = &B900
ASSERT MUSIC_B2_BASE   = &BA00

VGI_FRAMES = 17448

.vgi_map_lo
    EQUB &09, &7B, &A1, &31, &00, &00, &4A, &4B, &00, &00, &F4
.vgi_map_hi
    EQUB &B4, &9D, &C5, &A9, &91, &80, &8D, &CE, &BA, &B9, &BC
.vgi_map_rom
    EQUB &07, &07, &07, &07, &07, &87, &87, &07, &06, &05, &07

\ stream  0:  2283 bytes at &B409, region A
\ stream  1:  2998 bytes at &9D7B, region A
\ stream  2:  2218 bytes at &C5A1, region A
\ stream  3:  2776 bytes at &A931, region A
\ stream  4:  3195 bytes at &9100, region A
\ stream  5:  3402 bytes at &8000, region ANDY
\ stream  6:   596 bytes at &8D4A, region ANDY
\ stream  7:  1173 bytes at &CE4B, region A
\ stream  8:  1351 bytes at &BA00, region B2
\ stream  9:  1273 bytes at &B900, region B1
\ stream 10:  2221 bytes at &BCF4, region A
