\ Generated by tools/export_palette.py - do not edit.
\ the C64's sixteen as the bytes setup_display writes to &FE23 (VideoNuLA palette).
\ ASCENDING, entry 0 first, which is the order the loop runs in and
\ the order VideoNuLA requires: each entry is TWO bytes, [index|red]
\ then [green|blue], and they must reach &FE23 in that order.

PAL_BYTES = 32
.pal_data
    EQUB &00, &00    \ logical 0  = &000000
    EQUB &1F, &FF    \ logical 1  = &FFFFFF
    EQUB &26, &32    \ logical 2  = &68372B
    EQUB &37, &AB    \ logical 3  = &70A4B2
    EQUB &46, &38    \ logical 4  = &6F3D86
    EQUB &55, &84    \ logical 5  = &588D43
    EQUB &63, &27    \ logical 6  = &352879
    EQUB &7B, &C6    \ logical 7  = &B8C76F
    EQUB &86, &42    \ logical 8  = &6F4F25
    EQUB &94, &30    \ logical 9  = &433900
    EQUB &A9, &65    \ logical 10 = &9A6759
    EQUB &B4, &44    \ logical 11 = &444444
    EQUB &C6, &66    \ logical 12 = &6C6C6C
    EQUB &D9, &D8    \ logical 13 = &9AD284
    EQUB &E6, &5B    \ logical 14 = &6C5EB5
    EQUB &F9, &99    \ logical 15 = &959595
