\ Generated by tools/export_palette.py - do not edit.
\ the Amstrad's sixteen mode 0 pens as the bytes setup_display writes to &FE23 (VideoNuLA palette).
\ ASCENDING, entry 0 first, which is the order the loop runs in and
\ the order VideoNuLA requires: each entry is TWO bytes, [index|red]
\ then [green|blue], and they must reach &FE23 in that order.

PAL_BYTES = 32
.pal_data
    EQUB &00, &00    \ logical 0  = &000000
    EQUB &18, &00    \ logical 1  = &800000
    EQUB &2F, &F8    \ logical 2  = &FFFF80
    EQUB &30, &08    \ logical 3  = &000080
    EQUB &40, &80    \ logical 4  = &008000
    EQUB &5F, &00    \ logical 5  = &FF0000
    EQUB &6F, &88    \ logical 6  = &FF8080
    EQUB &70, &0F    \ logical 7  = &0000FF
    EQUB &88, &8F    \ logical 8  = &8080FF
    EQUB &9F, &FF    \ logical 9  = &FFFFFF
    EQUB &A0, &FF    \ logical 10 = &00FFFF
    EQUB &B8, &80    \ logical 11 = &808000
    EQUB &C0, &FF    \ logical 12 = &00FFFF
    EQUB &D0, &8F    \ logical 13 = &0080FF
    EQUB &E8, &0F    \ logical 14 = &8000FF
    EQUB &F0, &00    \ logical 15 = &000000
