\ Generated by tools/export_palette.py - do not edit.
\ assets/art/palette.png as the bytes setup_display writes to &FE21 (Video ULA).
\ Written high entry to low, which is the order the loop runs in.

PAL_BYTES = 16
.pal_data
    EQUB &F0         \ logical 15 = &FFFFFF
    EQUB &E1         \ logical 14 = &00FFFF
    EQUB &D2         \ logical 13 = &FF00FF
    EQUB &C3         \ logical 12 = &0000FF
    EQUB &B4         \ logical 11 = &FFFF00
    EQUB &A5         \ logical 10 = &00FF00
    EQUB &96         \ logical 9  = &FF0000
    EQUB &87         \ logical 8  = &000000
    EQUB &70         \ logical 7  = &FFFFFF
    EQUB &61         \ logical 6  = &00FFFF
    EQUB &52         \ logical 5  = &FF00FF
    EQUB &43         \ logical 4  = &0000FF
    EQUB &34         \ logical 3  = &FFFF00
    EQUB &25         \ logical 2  = &00FF00
    EQUB &16         \ logical 1  = &FF0000
    EQUB &07         \ logical 0  = &000000
